
[functions.send-request-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-request-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-request-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-request-email/*.html" ]

[functions.route-distance]
enabled = true
verify_jwt = false
import_map = "./functions/route-distance/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/route-distance/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/route-distance/*.html" ]

[functions.admin-route-distance]
enabled = true
verify_jwt = false
import_map = "./functions/admin-route-distance/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-route-distance/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-route-distance/*.html" ]

[functions.get-request-status]
enabled = true
verify_jwt = false
entrypoint = "./functions/get-request-status/index.ts"

[functions.create-embedded-checkout]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-embedded-checkout/index.ts"

[functions.send-invoice-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-invoice-email/index.ts"

[functions.stripe-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/stripe-webhook/index.ts"

[functions.send-order-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-order-email/index.ts"

[functions.update-request-status]
enabled = true
verify_jwt = false
entrypoint = "./functions/update-request-status/index.ts"

[functions.client-quote-action]
enabled = true
verify_jwt = false
entrypoint = "./functions/client-quote-action/index.ts"

[functions.create-additional-invoice]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-additional-invoice/index.ts"
