import { customerPortalUrl, emailButton, emailPanel, escapeEmail, recipientGreeting, renderCustomerEmailShell } from "./customer-email.mjs";

export const REVIEW_DESTINATIONS = Object.freeze({google:"https://g.page/r/CeY4X1XsHwJFEAI/review"});

export const TEMPLATE_SPECIFICATIONS = Object.freeze({
  request_received:{category:"Intake",purpose:"Acknowledges that APS received a request without implying confirmation.",trigger:"Request created",classification:"Automatic",eyebrow:"REQUEST RECEIVED",title:"Your Request Was Received",cta:"View My Request",tab:"overview",fields:["customer first name","request reference","service type","requested date","requested time","secure request URL"]},
  quote_ready:{category:"Quote",purpose:"Presents the current reviewed quote and directs the customer to respond.",trigger:"Current quote ready",classification:"Workflow / Admin",eyebrow:"QUOTE READY",title:"Your Quote Is Ready",cta:"Review Quote",tab:"quote-payment",fields:["customer name","request reference","service","requested date/time","preferred contact","quote number and version","quote line items","quantity","rate","line totals","quote total","secure Quote & Payment URL"]},
  awaiting_payment_reminder:{category:"Payment",purpose:"Reminds the customer of a legitimate amount currently due.",trigger:"Payment due reminder",classification:"Workflow",eyebrow:"PAYMENT DUE",title:"Your Payment Is Ready",cta:"Make Payment",tab:"quote-payment",fields:["customer name","request reference","invoice number","amount due","paid to date","legitimate balance due","secure Quote & Payment URL"]},
  payment_received:{category:"Payment",purpose:"Confirms a recorded payment without describing a partial payment as paid in full.",trigger:"Stripe/payment recorded",classification:"Automatic / Workflow",eyebrow:"PAYMENT RECEIVED",title:"Your Payment Has Been Received",cta:"View Payment Status",tab:"quote-payment",fields:["customer name","request reference","payment amount","payment date","paid to date","legitimate balance due if partial","secure Quote & Payment URL"]},
  final_invoice:{category:"Payment",purpose:"Presents a supplemental or final legitimate balance.",trigger:"Supplemental/final invoice created",classification:"Workflow",eyebrow:"FINAL BALANCE DUE",title:"Your Remaining Balance Is Ready",cta:"Review & Pay Balance",tab:"quote-payment",fields:["customer name","request reference","invoice number","additional charges","amount already paid","remaining balance","secure Quote & Payment URL"]},
  appointment_confirmed:{category:"Appointment",purpose:"Confirms the current service-appropriate appointment details.",trigger:"Appointment confirmed",classification:"Workflow / Admin",eyebrow:"APPOINTMENT CONFIRMED",title:"Your Appointment Is Confirmed",cta:"View Appointment",tab:"fulfillment",fields:["customer name","request reference","service","current confirmed appointment date","current confirmed appointment time","physical location when applicable","RON/session details when applicable","preparation instructions","secure Appointment/Fulfillment URL"]},
  appointment_reminder:{category:"Appointment",purpose:"Reminds the customer of the current confirmed appointment.",trigger:"Appointment reminder",classification:"Workflow",eyebrow:"APPOINTMENT REMINDER",title:"Your Appointment Is Coming Up",cta:"View Appointment",tab:"fulfillment",fields:["customer name","request reference","service","current confirmed date/time","service-appropriate location/session information","preparation instructions","secure Appointment/Fulfillment URL"]},
  appointment_rescheduled:{category:"Appointment",purpose:"Shows the newly confirmed appointment rather than the former requested time.",trigger:"Appointment rescheduled",classification:"Workflow / Admin",eyebrow:"APPOINTMENT UPDATED",title:"Your Appointment Has Been Updated",cta:"View Updated Appointment",tab:"fulfillment",fields:["customer name","request reference","service","CURRENT confirmed appointment date","CURRENT confirmed appointment time","physical location when applicable","RON/session details when applicable","preparation instructions","secure Appointment/Fulfillment URL"]},
  ron_session_ready:{category:"RON",purpose:"Provides current secure-session and preparation details.",trigger:"RON session ready",classification:"Workflow / Admin",eyebrow:"RON SESSION READY",title:"Your Online Notary Session Is Ready",cta:"View Appointment",tab:"fulfillment",fields:["customer name","request reference","current confirmed date/time","secure-session or next-step information","identity/document preparation instructions","secure Appointment/Fulfillment URL"]},
  mobile_appointment_confirmation:{category:"Mobile",purpose:"Confirms current mobile appointment and physical-service details.",trigger:"Mobile appointment confirmed",classification:"Workflow / Admin",eyebrow:"APPOINTMENT CONFIRMED",title:"Your Mobile Appointment Is Confirmed",cta:"View Appointment",tab:"fulfillment",fields:["customer name","request reference","current confirmed date/time","service address/location","preparation instructions","secure Appointment/Fulfillment URL"]},
  completed_scan_delivery:{category:"Documents",purpose:"Directs the customer to intentionally released completed scans.",trigger:"Completed scans released",classification:"Workflow / Admin",eyebrow:"COMPLETED SCANS",title:"Your Completed Scans Are Ready",cta:"View Documents",tab:"documents",fields:["customer name","request reference","service","customer-released scan names","delivery wording","secure Documents URL"]},
  document_delivery:{category:"Documents",purpose:"Directs the customer to intentionally released customer documents.",trigger:"Customer document released",classification:"Workflow / Admin",eyebrow:"DOCUMENTS READY",title:"Your Documents Are Ready",cta:"View Documents",tab:"documents",fields:["customer name","request reference","service","customer-released document names","delivery wording","secure Documents URL"]},
  document_needed_for_quote:{category:"Documents",purpose:"Requests the source document needed to prepare an accurate quote.",trigger:"Administrator determines a document is required for quoting",classification:"Manual / Admin",eyebrow:"DOCUMENT NEEDED",title:"A Document Is Needed for Your Quote",cta:"Upload Document",tab:"documents",fields:["customer first name","request reference","service","secure Documents URL"]},
  document_received_under_review:{category:"Documents",purpose:"Optionally acknowledges that a supplied document was received and is being reviewed.",trigger:"Administrator confirms receipt",classification:"Manual / Admin",eyebrow:"DOCUMENT RECEIVED",title:"Your Document Is Under Review",cta:"View Documents",tab:"documents",fields:["customer first name","request reference","service","secure Documents URL"]},
  service_changed_appointment_conversion:{category:"Appointment",purpose:"Explains an approved RON/Mobile conversion while preserving the APS request history.",trigger:"Administrator completes same-request service conversion",classification:"Manual / Admin",eyebrow:"SERVICE CHANGED",title:"Your Service Was Updated",cta:"View Updated Request",tab:"fulfillment",fields:["customer first name","request reference","previous service","new service","administrator message","current scheduling and payment information"]},
  order_completed:{category:"Completion",purpose:"Confirms service completion and directs the customer to the appropriate final section.",trigger:"Order/service completed",classification:"Workflow / Admin",eyebrow:"SERVICE COMPLETED",title:"Your Request Is Complete",cta:"View Completed Request",tab:"overview",fields:["customer name","request reference","service","completion date","released deliverables when applicable","appropriate final portal destination"]},
  review_request:{category:"Reputation",purpose:"Neutral optional review invitation after legitimate completion, release, and financial resolution.",trigger:"Review request eligible; administrator sends once",classification:"Post-completion / Admin",eyebrow:"THANK YOU",title:"Share Your Experience",cta:"Share Feedback",tab:"overview",fields:["customer first name","request reference","service","owner-configured review destination"]},
  cancellation:{category:"Cancellation",purpose:"Communicates the applicable cancellation decision or state clearly.",trigger:"Cancellation confirmed",classification:"Workflow / Customer Action / Admin",eyebrow:"CANCELLATION CONFIRMED",title:"Your Request Was Cancelled",cta:"View My Request",tab:"overview",fields:["customer name","request reference","service","customer-facing cancellation wording","secure request URL"]},
  cancellation_request_received:{category:"Cancellation",purpose:"Acknowledges a cancellation request without promising cancellation or a refund.",trigger:"Customer cancellation request persisted",classification:"Automatic / Customer Action",eyebrow:"CANCELLATION REQUEST RECEIVED",title:"We Received Your Request",cta:"View My Request",tab:"overview",fields:["customer name","request reference","service","customer-supplied reason","review expectation","secure request URL"]},
  cancellation_confirmed_no_payment:{category:"Cancellation",purpose:"Confirms an approved cancellation when no payment refund is due.",trigger:"Administrator cancellation review completed",classification:"Send & Update Status / Admin",eyebrow:"CANCELLATION CONFIRMED",title:"Your Request Was Cancelled",cta:"View My Request",tab:"overview",fields:["customer name","request reference","service","effective date","customer-facing decision explanation","secure request URL"]},
  cancellation_confirmed_refund_due:{category:"Cancellation",purpose:"Confirms cancellation and explains that an approved refund still requires authoritative processing.",trigger:"Administrator approves cancellation with refund due",classification:"Send & Update Status / Admin",eyebrow:"CANCELLATION CONFIRMED",title:"Your Refund Is Pending",cta:"View Payment Status",tab:"quote-payment",fields:["customer name","request reference","service","approved refund amount","original payment method","customer-facing explanation","secure Quote & Payment URL"]},
  refund_due:{category:"Refund",purpose:"Explains an approved refund that has not yet been completed by the authoritative payment path.",trigger:"Refund approved and pending",classification:"Send Message / Admin",eyebrow:"REFUND PENDING",title:"Your Refund Is Being Processed",cta:"View Payment Status",tab:"quote-payment",fields:["customer name","request reference","approved refund amount","payment method","current refund state","secure Quote & Payment URL"]},
  refund_processed:{category:"Refund",purpose:"Confirms a refund only after an authoritative provider or offline record shows completion.",trigger:"Authoritative refund completion persisted",classification:"Automatic / Workflow",eyebrow:"REFUND PROCESSED",title:"Your Refund Was Processed",cta:"View Payment Status",tab:"quote-payment",fields:["customer name","request reference","refund amount","processed date","original payment method","provider/reference identifier when customer-safe","secure Quote & Payment URL"]},
  late_retained_amount_explanation:{category:"Refund",purpose:"Explains an administrator-reviewed retained amount after work, reserved capacity, or nonrecoverable cost.",trigger:"Cancellation/refund review establishes a retained amount",classification:"Send Message / Admin",eyebrow:"CANCELLATION REVIEW",title:"Your Cancellation Amount Was Reviewed",cta:"View Payment Status",tab:"quote-payment",fields:["customer name","request reference","service","amount paid","amount refunded","customer-facing retained amount explanation","secure Quote & Payment URL"]},
  aps_unable_to_fulfill:{category:"Cancellation",purpose:"Explains that APS cannot fulfill the service and states the reviewed next financial step.",trigger:"APS-initiated inability-to-fulfill decision",classification:"Send & Update Status / Admin",eyebrow:"SERVICE UPDATE",title:"APS Is Unable to Fulfill This Request",cta:"View My Request",tab:"overview",fields:["customer name","request reference","service","customer-facing reason","refund/next-step state","secure request URL"]},
  general_customer_message:{category:"General",purpose:"Sends an administrator-authored customer update within the request context.",trigger:"Admin composed",classification:"Admin",eyebrow:"APS UPDATE",title:"An Update About Your Request",cta:"View My Request",tab:"overview",fields:["customer name","request reference","service","administrator-maintained body wording","secure request URL"]},
  business_password_reset:{category:"Account / Security",purpose:"Provides a secure password-reset link to an eligible Business Portal user.",trigger:"Eligible Business Portal user requests password recovery",classification:"Automatic / Security",eyebrow:"BUSINESS PORTAL SECURITY",title:"Reset your password",cta:"Reset My Password",tab:"account",fields:["authorized Business Portal user","organization","recipient email","one-time secure recovery URL","limited-time expiration statement","safe delivery audit metadata"]},
  lsa_request_received:{category:"Loan Signing",purpose:"Acknowledges receipt without confirming acceptance.",trigger:"Loan Signing request received",classification:"Automatic / Workflow",eyebrow:"LOAN SIGNING REQUEST",title:"Your Request Was Received",cta:"View Request",tab:"overview",fields:["customer name","request reference","assignment type","requested appointment","secure request URL"]},
  lsa_information_needed:{category:"Loan Signing",purpose:"Requests missing assignment information neutrally.",trigger:"Admin identifies missing assignment facts",classification:"Manual / Admin",eyebrow:"INFORMATION NEEDED",title:"Assignment Information Is Needed",cta:"View Request",tab:"overview",fields:["customer name","request reference","missing information","customer-safe instructions","secure request URL"]},
  lsa_assignment_confirmed:{category:"Loan Signing",purpose:"Confirms an accepted assignment and next steps.",trigger:"Assignment accepted",classification:"Manual / Admin",eyebrow:"ASSIGNMENT CONFIRMED",title:"Your Loan Signing Is Confirmed",cta:"View Appointment",tab:"fulfillment",fields:["customer name","request reference","appointment details","preparation instructions","secure fulfillment URL"]},
  lsa_signer_confirmation:{category:"Loan Signing",purpose:"Provides a neutral signer-confirmation update.",trigger:"Signer confirmation reviewed",classification:"Manual / Admin",eyebrow:"SIGNER CONFIRMATION",title:"Signer Confirmation Update",cta:"View Assignment",tab:"fulfillment",fields:["customer name","request reference","customer-safe confirmation state","next step","secure fulfillment URL"]},
  lsa_cancellation_under_review:{category:"Loan Signing",purpose:"Acknowledges cancellation review without promising a charge or refund.",trigger:"Cancellation exception recorded",classification:"Manual / Admin",eyebrow:"CANCELLATION REVIEW",title:"Your Request Is Under Review",cta:"View Request",tab:"overview",fields:["customer name","request reference","review state","customer-safe next step","secure request URL"]},
  lsa_signing_not_completed:{category:"Loan Signing",purpose:"Explains neutrally that signing did not complete.",trigger:"No-sign or incomplete outcome recorded",classification:"Manual / Admin",eyebrow:"SIGNING FOLLOW-UP",title:"Additional Review Is Needed",cta:"View Assignment",tab:"fulfillment",fields:["customer name","request reference","customer-safe outcome","next step","secure fulfillment URL"]},
  lsa_additional_appointment_needed:{category:"Loan Signing",purpose:"Requests a resign or return visit without exposing blame.",trigger:"Additional visit authorized",classification:"Manual / Admin",eyebrow:"APPOINTMENT NEEDED",title:"An Additional Signing Appointment Is Needed",cta:"View Appointment",tab:"fulfillment",fields:["customer name","request reference","appointment status","customer-safe financial state","secure fulfillment URL"]},
  lsa_exception_resolved:{category:"Loan Signing",purpose:"Communicates a reviewed customer-safe exception result.",trigger:"Operational and financial review resolved",classification:"Manual / Admin",eyebrow:"REVIEW RESOLVED",title:"Your Assignment Review Is Complete",cta:"View Request",tab:"overview",fields:["customer name","request reference","customer-safe explanation","billing/refund next step when authorized","secure request URL"]},
});

export const SYNTHETIC_TEMPLATE_CONTEXT = Object.freeze({requestId:"demo-request",reference:"APS-DEMO1234",customer:{first_name:"Jane",last_name:"Sample"},serviceType:"mobile",serviceName:"Mobile Notary",previousServiceName:"Remote Online Notary",messageBody:"APS will confirm the updated appointment after reviewing the destination-service requirements.",requestedDate:"August 20, 2026",requestedTime:"1:00–2:00 PM CT",appointmentDate:"August 21, 2026",appointmentTime:"2:00 PM CT",appointmentLocation:"123 Sample Avenue, Waxahachie, TX 75165",appointmentInstructions:"Please have a valid photo ID and all unsigned documents ready.",appointmentLink:"",resetUrl:"https://alignedprintscan.com/business-reset-password.html#synthetic-preview",preferredContact:"Email",quoteNumber:"Q-DEMO1234-v2",quoteVersion:"2",quoteAmount:"$45.00",quoteItems:[{name:"Mobile notary appointment",quantity:1,rate:"$45.00",total:"$45.00"}],invoiceNumber:"INV-DEMO1234-01",paymentAmount:"$25.00",paymentDate:"August 13, 2026",paidAmount:"$25.00",balanceDue:"$20.00",releasedDocumentNames:["sample-customer-copy.pdf"],completionDate:"August 21, 2026",siteUrl:"https://alignedprintscan.com"});

function appointmentRows(context) { const rows=[["Reference",context.reference],["Service",context.serviceName],["Confirmed Date",context.appointmentDate],["Confirmed Time",context.appointmentTime]]; if(context.serviceType==="ron") rows.push(["Secure Session",context.appointmentLink||"Available in your secure request"]); else rows.push(["Service Address / Location",context.appointmentLocation]); rows.push(["Preparation",context.appointmentInstructions]); return rows; }
function quoteTable(items=[]) { if(!items.length)return ""; return `<table width="100%" cellpadding="8" cellspacing="0" role="presentation" style="border-collapse:collapse;margin:18px 0"><tr style="background:#161c4d;color:#fff"><th align="left">Service Item</th><th>Qty</th><th>Rate</th><th>Total</th></tr>${items.map(item=>`<tr><td style="border:1px solid #e7dcc5">${escapeEmail(item.name)}</td><td align="center" style="border:1px solid #e7dcc5">${escapeEmail(item.quantity)}</td><td align="right" style="border:1px solid #e7dcc5">${escapeEmail(item.rate)}</td><td align="right" style="border:1px solid #e7dcc5">${escapeEmail(item.total)}</td></tr>`).join("")}</table>`; }
function detailContent(key, context) { if(key==="business_password_reset")return ""; if(["appointment_confirmed","appointment_reminder","appointment_rescheduled","ron_session_ready","mobile_appointment_confirmation"].includes(key)) return emailPanel(appointmentRows(context)); if(key==="quote_ready") return emailPanel([["Reference",context.reference],["Client",`${context.customer?.first_name||""} ${context.customer?.last_name||""}`.trim()],["Service",context.serviceName],["Requested",`${context.requestedDate} · ${context.requestedTime}`],["Preferred Contact",context.preferredContact],["Quote",`${context.quoteNumber} · $${String(context.quoteAmount).replace(/^\$/,'')}`]])+quoteTable(context.quoteItems); if(["awaiting_payment_reminder","payment_received","final_invoice"].includes(key)) return emailPanel([["Reference",context.reference],["Invoice",context.invoiceNumber],["Payment Recorded",context.paymentAmount],["Payment Date",context.paymentDate],["Paid to Date",context.paidAmount],["Balance Due",context.balanceDue]]); if(["document_delivery","completed_scan_delivery"].includes(key)) return emailPanel([["Reference",context.reference],["Service",context.serviceName],["Released Documents",(context.releasedDocumentNames||[]).join(", ")]]); if(key==="order_completed") return emailPanel([["Reference",context.reference],["Service",context.serviceName],["Completed",context.completionDate],["Released Documents",(context.releasedDocumentNames||[]).join(", ")]]); return emailPanel([["Reference",context.reference],["Service",context.serviceName],["Requested Date",context.requestedDate],["Requested Time",context.requestedTime]]); }
export function renderTemplateValues(value, context) { const values={request_reference:context.reference,customer_first_name:context.customer?.first_name||"",customer_name:[context.customer?.first_name,context.customer?.last_name].filter(Boolean).join(" "),service_name:context.serviceName,previous_service_name:context.previousServiceName,message_body:context.messageBody,requested_date:context.requestedDate,requested_time:context.requestedTime,appointment_date:context.appointmentDate,appointment_time:context.appointmentTime,appointment_location:context.appointmentLocation,appointment_link:context.appointmentLink,quote_number:context.quoteNumber,quote_amount:String(context.quoteAmount).replace(/^\$/,""),invoice_number:context.invoiceNumber,payment_amount:context.paymentAmount,balance_due:context.balanceDue,amount_paid:context.paidAmount,completion_date:context.completionDate,released_document_names:(context.releasedDocumentNames||[]).join(", ")}; return String(value||"").replace(/{{\s*([a-z0-9_]+)\s*}}/gi,(_,key)=>values[key]??""); }
/** @param {{template:any,context?:any,editedBody?:string|null,subjectOverride?:string|null}} options */
export function renderFullTemplateEmail({template,context=SYNTHETIC_TEMPLATE_CONTEXT,editedBody=null,subjectOverride=null}) { const spec=TEMPLATE_SPECIFICATIONS[template.template_key]||TEMPLATE_SPECIFICATIONS.general_customer_message; const portal=context.actionUrl||(template.template_key==="review_request"?REVIEW_DESTINATIONS.google:template.template_key==="business_password_reset"?context.resetUrl:customerPortalUrl(context.siteUrl||"https://alignedprintscan.com",context.requestId,spec.tab)); const subject=subjectOverride||renderTemplateValues(template.subject_template||`${template.name}: {{request_reference}}`,context); let body=editedBody===null?renderTemplateValues(template.html_template||"",context):String(editedBody||""); body=body.replace(/<p>Hello[^<]*<\/p>/i,""); const greeting=`<p>${recipientGreeting(context.customer)}</p>`; const fullBody=`${greeting}${body}${detailContent(template.template_key,context)}${emailButton(portal,spec.cta)}`; return {subject,html:renderCustomerEmailShell({body:fullBody,preheader:subject,eyebrow:spec.eyebrow,title:spec.title,siteUrl:context.siteUrl}),spec,portal}; }
