import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { addressText, completeAddress, drivingRoute, geocodeAddress, routeCacheKey, routeMetrics, selectTravelTier } from "../supabase/functions/_shared/mobile-travel.mjs";

const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
const tiers=[{tier_key:"0-15",minimum_round_trip_miles:0,maximum_round_trip_miles:15,fee:0,sort_order:10},{tier_key:"16-20",minimum_round_trip_miles:15,maximum_round_trip_miles:20,fee:10,sort_order:20},{tier_key:"21+",minimum_round_trip_miles:20,maximum_round_trip_miles:null,fee:20,sort_order:30}];

test("structured Mobile address is the only route destination",()=>{const address=completeAddress({street_address:"123 Test Lane",city:"Waxahachie",state:"tx",zip:"75165"});assert.equal(addressText(address),"123 Test Lane, Waxahachie, TX 75165");assert.equal(completeAddress({...address,zip:""}),null);});
test("ORS meters and seconds convert deterministically without display-rounding tier drift",()=>{const value=routeMetrics(8.37*1609.344,1020);assert.equal(value.one_way_miles,8.37);assert.equal(value.round_trip_miles,16.74);assert.equal(value.display_one_way_miles,8.4);assert.equal(value.display_round_trip_miles,16.7);assert.equal(value.display_duration_minutes,17);});
test("tier boundaries use unrounded round-trip miles",()=>{assert.equal(selectTravelTier(14.9999,tiers).tier_key,"0-15");assert.equal(selectTravelTier(15,tiers).tier_key,"0-15");assert.equal(selectTravelTier(15.0001,tiers).tier_key,"16-20");assert.equal(selectTravelTier(20,tiers).tier_key,"16-20");assert.equal(selectTravelTier(20.0001,tiers).tier_key,"21+");});
test("cache identity changes with origin or destination",async()=>{const a={street_address:"1 A St",city:"A",state:"TX",zip:"75001"},b={street_address:"2 B St",city:"B",state:"TX",zip:"75002"},c={...a,zip:"75003"};assert.equal(await routeCacheKey(a,b),await routeCacheKey(a,b));assert.notEqual(await routeCacheKey(a,b),await routeCacheKey(c,b));assert.notEqual(await routeCacheKey(a,b),await routeCacheKey(a,c));});
test("ORS calls use server authorization and discard provider payload",async()=>{const calls=[];const fetchImpl=async(url,init={})=>{calls.push({url:String(url),init});return String(url).includes("geocode")?new Response(JSON.stringify({features:[{geometry:{coordinates:[-96.8,32.4]}}]}),{status:200}):new Response(JSON.stringify({routes:[{summary:{distance:1609.344,duration:600}}],metadata:{secret:"discard"}}),{status:200});};const point=await geocodeAddress({street_address:"1 A St",city:"A",state:"TX",zip:"75001"},{apiKey:"test-server-key",fetchImpl});const route=await drivingRoute(point,[-96.7,32.5],{apiKey:"test-server-key",fetchImpl});assert.equal(route.one_way_miles,1);assert.equal(calls[0].init.headers.Authorization,"test-server-key");assert.deepEqual(JSON.parse(calls[1].init.body).coordinates,[point,[-96.7,32.5]]);assert.equal(route.secret,undefined);});
test("ORS failures remain actionable and manual-safe",async()=>{for(const status of [429,500])await assert.rejects(()=>geocodeAddress({street_address:"1 A",city:"A",state:"TX",zip:"75001"},{apiKey:"x",fetchImpl:async()=>new Response("{}",{status})}),/manually|rate limited/i);await assert.rejects(()=>drivingRoute([1,2],[3,4],{apiKey:"x",fetchImpl:async()=>new Response(JSON.stringify({routes:[]}),{status:200})}),/No driving route/);});
test("migration keeps origins private, one default, and history after deactivation",async()=>{const sql=await read("supabase/migrations/20260817002018_mobile_travel_ors.sql");assert.match(sql,/travel_origins_one_active_default/);assert.match(sql,/on delete set null/);assert.match(sql,/origin_address jsonb/);assert.match(sql,/enable row level security/g);assert.match(sql,/public\.is_admin\(\)/);assert.doesNotMatch(sql,/to anon/);});
test("server function enforces admin auth, server-only key, caching, quote locks, supplemental invoices, and Timeline",async()=>{const source=await read("supabase/functions/admin-route-distance/index.ts");assert.match(source,/requireAdmin/);assert.match(source,/OPENROUTESERVICE_API_KEY/);assert.match(source,/cacheKey/);assert.match(source,/apply_to_quote/);assert.match(source,/already been sent or approved/);assert.match(source,/create-additional-invoice/);assert.match(source,/mobile_travel_applied/);assert.match(source,/apply_manual/);assert.doesNotMatch(await read("assets/js/admin.js"),/OPENROUTESERVICE_API_KEY|ORS_API_KEY/);});
test("Mobile-only UI auto-loads structured destination and requires explicit quote action",async()=>{const [admin,settings,html]=await Promise.all([read("assets/js/admin.js"),read("assets/js/admin-v3.js"),read("admin-dashboard.html")]);assert.match(admin,/selectedRequest\.service_type === "mobile"/);assert.match(admin,/Travel Distance &amp; Quote/);assert.match(admin,/loadMobileTravelCard/);assert.match(admin,/Add to Quote/);assert.match(admin,/Manual mileage\/travel charge fallback/);assert.match(settings,/Saved Travel Origins/);assert.match(settings,/Set Default/);assert.match(settings,/Deactivate/);assert.match(html,/20260817-mobile-travel-ors/);});
test("conversion architecture is reused and historical financial data is not rewritten",async()=>{const [travel,conversion]=await Promise.all([read("supabase/functions/admin-route-distance/index.ts"),read("supabase/functions/admin-service-adjustment/index.ts")]);assert.match(conversion,/request_service_conversions/);assert.match(conversion,/create-additional-invoice/);assert.match(travel,/service_type!=="mobile"/);assert.match(travel,/invoice_id=is\.null/);assert.doesNotMatch(travel,/delete.*(invoices|request_payments|mobile_travel_calculations)/i);});
test("handbook assets are outside this release implementation",async()=>{const status=await read("admin-dashboard.html");assert.doesNotMatch(status,/handbook/i);});
