import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { readFile } from "node:fs/promises";
import test from "node:test";

const require = createRequire(import.meta.url);
const { derive } = require("../assets/js/proof-return-state.js");
const read = path => readFile(new URL(`../${path}`, import.meta.url), "utf8");
const tx = patch => ({ id: "tx", activation_state: "activated", ...patch });
const asset = patch => ({ id: "asset", asset_type: "completed_document", ...patch });
const file = patch => ({ id: "file", uploaded_by: "proof", document_classification: "completed_notarized_document", is_active: true, ...patch });

test("1 Proof operator action opens a new tab", async()=>assert.match(await read("assets/js/admin.js"),/proof-open-dashboard[\s\S]+target="_blank"/));
test("2 APS request remains available", async()=>assert.match(await read("assets/js/admin.js"),/aps:proof-opened:/));
test("3 handoff guidance renders for RON control panel", async()=>assert.match(await read("assets/js/admin.js"),/proofReturnGuidance/));
test("4 non-RON requests have no Proof control panel", async()=>assert.match(await read("assets/js/admin.js"),/selectedRequest\.service_type === "ron" \? '<section/));
test("5 live work is presented as in progress",()=>assert.equal(derive({transaction:tx({proof_status:"received"})}).key,"in_progress"));
test("6 Proof complete without file waits",()=>assert.equal(derive({transaction:tx({completed_at:"now"})}).key,"completed_waiting"));
test("7 available file has retrieval action",()=>assert.equal(derive({transaction:tx({completed_at:"now",completed_assets_available:true})}).key,"available"));
test("8 retrieved staged file is pending review",()=>assert.equal(derive({transaction:tx({completed_at:"now"}),files:[file({review_state:"pending"})]}).key,"ready_review"));
test("9 review action deep-links to Documents",()=>assert.equal(derive({transaction:tx(),files:[file({review_state:"pending"})]}).tab,"documents"));
test("10 exact returned document identifier is targeted",()=>assert.equal(derive({transaction:tx(),files:[file({id:"exact"})]}).documentId,"exact"));
test("11 reviewed document is ready for explicit release",()=>assert.equal(derive({transaction:tx(),files:[file({review_state:"approved"})]}).key,"ready_release"));
test("12 released document is authoritative",()=>assert.equal(derive({transaction:tx(),files:[file({review_state:"approved",customer_visible:true,eligible_for_delivery:true})]}).key,"released"));
test("13 completed request requires no action",()=>assert.equal(derive({request:{workflow_status:"completed"},transaction:tx(),files:[file({customer_visible:true,eligible_for_delivery:true})]}).key,"completed"));
test("14 Proof completion never means ready for review",()=>assert.notEqual(derive({transaction:tx({completed_at:"now"})}).key,"ready_review"));
test("15 reviewed but unreleased never means released",()=>assert.notEqual(derive({transaction:tx(),files:[file({review_state:"approved"})]}).key,"released"));
test("16 completed-document-ready notification exists",async()=>assert.match(await read("supabase/migrations/20260815083242_proof_return_operator_review.sql"),/Completed notarized document ready for review/));
test("17 notification stores document deep-link target",async()=>assert.match(await read("supabase/migrations/20260815083242_proof_return_operator_review.sql"),/target_document_id/));
test("18 existing sound preference remains authoritative",async()=>assert.match(await read("assets/js/admin-notifications.js"),/soundEnabled\(\)[\s\S]+ding/));
test("19 notification delivery remains deduplicated",async()=>assert.match(await read("supabase/migrations/20260815083242_proof_return_operator_review.sql"),/on conflict\(dedupe_key\) do nothing/));
test("20 Sync Proof Status remains retrieval-only wording",async()=>assert.match(await read("assets/js/admin.js"),/Sync Proof Status retrieves the latest state/));
test("21 completed document retrieval remains idempotent",async()=>assert.match(await read("supabase/functions/_shared/proof/completed-asset-lifecycle.ts"),/retrieval_state === "retrieved"\) return result\(asset, true\)/));
test("22 webhook idempotency remains present",async()=>assert.match(await read("supabase/functions/_shared/proof/webhook-lifecycle.ts"),/duplicate/));
test("23 focus refresh is bounded and read-only",async()=>{const source=await read("assets/js/admin.js");assert.match(source,/now - proofReturnRefreshAt < 15000/);assert.match(source,/loadProofControlPanel\(\)/);});
test("24 staged Timeline event is deduplicated",async()=>assert.match(await read("supabase/functions/_shared/proof/completed-asset-repository.ts"),/metadata-%3E%3Erequest_file_id/));
test("25 completed document storage identity is stable",async()=>assert.match(await read("supabase/functions/_shared/proof/completed-asset-repository.ts"),/proof-completed\/\$\{asset\.id\}\.pdf/));
test("26 notification dedupe is request-document scoped",async()=>assert.match(await read("supabase/migrations/20260815083242_proof_return_operator_review.sql"),/proof-review:/));
test("27 completed Proof document stays hidden before release",async()=>assert.match(await read("supabase/functions/_shared/proof/completed-asset-repository.ts"),/customer_visible: false/));
test("28 released completed documents remain customer visible",async()=>assert.match(await read("assets/js/script.js"),/Completed Notarized Documents/));
test("29 source and completed documents remain separate",async()=>assert.match(await read("supabase/functions/_shared/proof/completed-asset-repository.ts"),/source file not overwritten|proof-completed/));
test("30 audit documents remain internal",async()=>assert.match(await read("supabase/functions/_shared/proof/completed-asset-repository.ts"),/"internal_document"/));
test("31 RON stepper retains all post-session stages",async()=>{const source=await read("assets/js/admin.js");for(const label of ["Proof Completion","Completed Document Return","APS Review","Customer Release","APS Completion"])assert.match(source,new RegExp(label));});
test("32 authoritative action follows return state",()=>assert.equal(derive({transaction:tx(),files:[file({review_state:"pending"})]}).action,"Review Completed Document"));
test("33 completion gate remains separate",async()=>assert.match(await read("assets/js/admin.js"),/Authoritative Fulfillment Facts/));
test("34 financial state is not part of return mutations",async()=>assert.doesNotMatch(await read("assets/js/proof-return-state.js"),/invoice|payment|paid_amount|balance_due/));
test("35 Proof credentials remain server-side",async()=>{for(const path of ["assets/js/admin.js","assets/js/proof-return-state.js"])assert.doesNotMatch(await read(path),/PROOF_API_KEY|PROOF_WEBHOOK_SECRET/);});
test("36 customer portal filtering remains unchanged",async()=>assert.match(await read("supabase/functions/get-request-status/index.ts"),/file\.customer_visible === true &&\s*file\.eligible_for_delivery === true/));
