import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("Business login is focused and recovery pages are separate branded routes",async()=>{const[login,forgot,reset,css]=await Promise.all([read("business-login.html"),read("business-forgot-password.html"),read("business-reset-password.html"),read("assets/css/business-auth.css")]);assert.match(login,/businessLoginForm/);assert.match(login,/Forgot Password\?/);assert.match(login,/Return to Aligned Print &amp; Scan/);assert.doesNotMatch(login,/businessRecoveryForm|businessPasswordForm|New Password|Send Reset Link/);assert.match(forgot,/businessForgotForm/);assert.match(reset,/businessResetForm/);for(const page of [login,forgot,reset]){assert.match(page,/business-auth-shell/);assert.match(page,/business-auth-card/);assert.match(page,/business-auth-mark/);assert.match(page,/business-login\.js/)}assert.match(css,/business-auth-card/)});

test("auth client uses safe errors, valid recovery context, confirmation, and invitation preservation",async()=>{const js=await read("assets/js/business-login.js");assert.match(js,/The email or password you entered is incorrect/);assert.match(js,/If an approved account is associated with this email/);assert.match(js,/\["recovery","invite"\]/);assert.match(js,/business-reset-password\.html/);assert.match(js,/password!==confirmation/);assert.match(js,/minlength="12"|password\.length<12/);assert.match(js,/accept-release2-invitation/);assert.doesNotMatch(js,/error\.message[^\n]*safeStatus|resetPasswordForEmail/)});

test("recovery delivery is eligibility-scoped, idempotent, branded, audited, and token-secret",async()=>{const[edge,sql,preview]=await Promise.all([read("supabase/functions/business-password-recovery/index.ts"),read("supabase/migrations/20260820054656_release_7_2_business_password_recovery.sql"),read("supabase/functions/_shared/template-preview.mjs")]);assert.match(edge,/status=eq\.active/);assert.match(edge,/organizations!inner/);assert.match(edge,/admin\/generate_link/);assert.match(edge,/renderFullTemplateEmail/);assert.match(edge,/business_password_reset/);assert.match(edge,/admin_notifications/);assert.match(edge,/organization_activity/);assert.match(edge,/request_fingerprint/);assert.doesNotMatch(sql,/\b(reset_token|recovery_url|action_link)\b/i);assert.match(sql,/revoke all[\s\S]*from public,anon,authenticated/);assert.match(sql,/Business Account Password Reset/);assert.match(preview,/BUSINESS PORTAL SECURITY/);assert.match(preview,/Reset My Password/)});

test("public pages preserve order while applying the requested color and copy rhythm",async()=>{const[index,loan,business,styles]=await Promise.all([read("index.html"),read("loan-signing.html"),read("business-accounts.html"),read("assets/css/styles.css")]);const order=["How RON Works","Mobile Service","Document Support","Services for Businesses","About Aligned","Security & Technology","Ready to begin?"];let prior=-1;for(const text of order){const next=index.indexOf(text,prior+1);assert.ok(next>prior,text);prior=next}assert.match(index,/Document Support[\s\S]{0,700}section class="section cream business-discovery"/);assert.match(loan,/Professional loan signing support from preparation through return/);assert.match(loan,/class="text-cta"[^>]*>View Loan Signing Terms →/);assert.match(loan,/class="text-cta"[^>]*>Sign in to the Business Portal →/);assert.match(business,/Business Accounts can be configured around the services your organization actually uses/);assert.ok((business.match(/section class="section dark-band"/g)||[]).length>=3);assert.match(business,/section class="section cream" id="apply"/);assert.match(styles,/business-services-copy/);assert.match(styles,/text-cta/)});
