import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { buildRonSessionRows,filterRonSessions,sortRonSessions } from "../assets/js/ron-session-state.mjs";

const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
const base={id:"12345678-0000-0000-0000-000000000001",service_type:"ron",created_at:"2026-08-01T00:00:00Z",updated_at:"2026-08-02T00:00:00Z",workflow_status:"payment_received",appointment_date:"2026-08-15",appointment_time:"10:00:00",appointment_confirmed_at:"2026-08-02T00:00:00Z",document_state:"ready",customers:{first_name:"Jane",last_name:"Sample",email:"jane@example.com",phone:"2145550100"},ron_requests:[{number_of_signers:1}]};
const fixture=(overrides={})=>({requests:[{...base,...overrides},{...base,id:"87654321-0000-0000-0000-000000000002",service_type:"mobile"}],transactions:[],signers:[],assets:[],invoices:[{service_request_id:base.id,status:"open",amount_due:100,amount_paid:100,balance_due:0}],participants:[{service_request_id:base.id,participant_type:"signer",full_legal_name:"Jane Sample",email:"jane@example.com",identity_name_confirmed:true}],files:[{service_request_id:base.id,document_classification:"customer_document",review_state:"approved",is_active:true}]});

test("sidebar is clickable and SOON is removed",async()=>{const html=await read("admin-dashboard.html");assert.match(html,/href="#sessions" data-admin-view="sessions"/);assert.doesNotMatch(html,/RON Sessions[\s\S]{0,80}<em>SOON<\/em>/);});
test("inventory includes only RON requests and supports search and filters",()=>{const rows=buildRonSessionRows(fixture());assert.equal(rows.length,1);assert.equal(rows[0].payment.key,"paid");assert.equal(filterRonSessions(rows,{search:"jane@example.com"}).length,1);assert.equal(filterRonSessions(rows,{search:"nobody"}).length,0);assert.equal(filterRonSessions(rows,{payment:"awaiting_payment"}).length,0);});
test("appointment sort is chronological, not lexicographical",()=>{const one=buildRonSessionRows(fixture())[0];const two={...one,reference:"APS-2",appointmentAt:"2026-01-02T10:00:00"};assert.equal(sortRonSessions([one,two],"appointment_asc")[0].reference,"APS-2");});
test("Proof rejections remain distinct and completion does not imply release",()=>{const data=fixture();data.transactions=[{id:"tx",service_request_id:base.id,is_active:true,provider_detailed_status:"completed_with_rejections",completed_at:"2026-08-10T00:00:00Z"}];const row=buildRonSessionRows(data)[0];assert.equal(row.proof.key,"completed_with_rejections");assert.equal(row.documentReturn.key,"not_available");});
test("unreleased completed documents remain pending admin release",()=>{const data=fixture();data.files.push({service_request_id:base.id,document_classification:"completed_notarized_document",customer_visible:false,eligible_for_delivery:false,is_active:true});assert.equal(buildRonSessionRows(data)[0].documentReturn.key,"pending_review");});
test("reviewed completed documents become ready for explicit customer release",()=>{const data=fixture();data.transactions=[{id:"tx",service_request_id:base.id,is_active:true,activation_state:"activated",proof_status:"completed",completed_at:"2026-08-10T00:00:00Z",signer_configuration_state:"configured"}];data.files.push({service_request_id:base.id,document_classification:"completed_notarized_document",review_state:"approved",customer_visible:false,eligible_for_delivery:false,is_active:true});const row=buildRonSessionRows(data)[0];assert.equal(row.documentReturn.key,"ready_release");assert.equal(row.nextAction.label,"Release to Customer");assert.equal(row.nextAction.tab,"documents");});
test("Open Session routes to existing fulfillment Proof controls",async()=>{const admin=await read("assets/js/admin-v3.js");const detail=await read("assets/js/admin.js");assert.match(admin,/ron-open-session[\s\S]*openRequestFromModule/);assert.match(admin,/data-tab=\"\$\{safe\(row\.nextAction\.tab\|\|'fulfillment'\)\}/);assert.match(detail,/proofControlPanel[\s\S]*data-v3-tab-target="fulfillment"/);assert.match(detail,/selectedRequest\.service_type === "ron"/);});
test("customer portal and release/security boundaries remain intact",async()=>{const portal=await read("assets/js/script.js");const status=await read("supabase/functions/get-request-status/index.ts");const admin=await read("assets/js/admin-v3.js");assert.match(portal,/Completed Notarized Documents/);assert.match(status,/customer_visible === true &&\s*file\.eligible_for_delivery === true/);assert.doesNotMatch(admin,/PROOF_API_KEY|PROOF_WEBHOOK_SECRET|SUPABASE_SERVICE_ROLE_KEY/);});
test("responsive workspace prevents page-level overflow",async()=>{const css=await read("assets/css/admin-v3.css");assert.match(css,/@media \(max-width:520px\)[\s\S]*ron-session-controls/);assert.match(css,/ron-session-list,.ron-session-card \{ max-width:100%; overflow-wrap:anywhere; \}/);});
