import { requireRelease2Staff, serviceRows } from "../_shared/release2-auth.ts";
import { expectedPrintVolume, loanSigningCompletion } from "../_shared/loan-signing-fulfillment.mjs";
import { DEFAULT_LSA_POLICY, customerSafeException, financialResolutionPreview, resignReview, suggestedCancellationCharge, waitReview } from "../_shared/loan-signing-policy.mjs";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const uuid=(value:unknown)=>/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(String(value||""))?String(value):"";
const allowedRoles=new Set(["owner","administrator","operations","billing","support_read_only"]);
const tables={requirement:"loan_signing_requirements",package:"loan_signing_package_versions",stipulation:"loan_signing_stipulations",scanback:"loan_signing_scanbacks",return:"loan_signing_returns"} as const;
const fields={
  assignment:["instructions_reviewed_at","callback_confirmation_required","signer_confirmation_status","signer_contacted_at","signer_contact_method","signer_confirmation_note","printing_required","paper_size","sidedness","print_color","print_scaling","signing_set_count","borrower_copy_count","additional_copy_count","print_status","print_qc_status","borrower_copy_status","stacking_order_required","stacking_order_type","stacking_instructions","signing_outcome","post_signing_qc_status","arrival_at","signing_started_at","signing_ended_at","departure_at","resign_review_required","lsa_stage","scanbacks_required","approval_before_return_required","physical_return_required","return_method","round_trip_miles"],
  requirement:["requirement_group","requirement_key","title","instructions","applicability","status","source_type","source_note","customer_visible","sort_order","satisfied_at"],
  stipulation:["title","instructions","required","status","source_type","waiver_source","proof_file_id","proof_private","resolved_at"],
  scanback:["package_version_id","content_scope","instructions","status","qc_status","submitted_at","submission_method","recipient_destination","confirmation_reference","approval_source","approved_at","correction_instructions","resolved_at"],
  return:["return_method","destination_name","destination_department","destination_address_line1","destination_address_line2","destination_city","destination_state","destination_zip","delivery_window","delivery_instructions","carrier","label_required","label_provided","tracking_required","tracking_number","tracking_status","drop_off_location","drop_off_at","proof_required","proof_file_id","proof_recorded_at","status","completed_at"],
};
const pick=(body:Record<string,unknown>,names:string[])=>Object.fromEntries(names.filter((key)=>Object.hasOwn(body,key)).map((key)=>[key,body[key]]));
const policyMerge=(base:any,override:any={})=>({...base,...override,cancellation:{...base.cancellation,...(override.cancellation||{})},wait:{...base.wait,...(override.wait||{})},automatic_financial_action:false});
const operationalRoles=new Set(["owner","administrator","operations"]),financialRoles=new Set(["owner","administrator","billing"]);
const mayApproveFinancial=(profile:any)=>profile.role==="owner"||profile.permissions?.approve_lsa_financials===true||(profile.role==="administrator"&&profile.permissions?.approve_lsa_financials!==false);

async function snapshot(requestId:string){
  const assignments=await serviceRows(`loan_signing_assignments?select=*&service_request_id=eq.${requestId}&limit=1`); const assignment=assignments[0];
  if(!assignment)throw new Error("Loan Signing assignment was not found."); const id=assignment.id;
  const [requirements,packages,stipulations,scanbacks,returns,invoices,exceptions,visits,charges,resolutions,organizationTerms]=await Promise.all([
    serviceRows(`loan_signing_requirements?select=*&loan_signing_assignment_id=eq.${id}&order=requirement_group,sort_order`),
    serviceRows(`loan_signing_package_versions?select=*&loan_signing_assignment_id=eq.${id}&order=version_number.desc`),
    serviceRows(`loan_signing_stipulations?select=*&loan_signing_assignment_id=eq.${id}&order=created_at`),
    serviceRows(`loan_signing_scanbacks?select=*&loan_signing_assignment_id=eq.${id}&order=created_at.desc`),
    serviceRows(`loan_signing_returns?select=*&loan_signing_assignment_id=eq.${id}&order=created_at.desc`),
    serviceRows(`invoices?select=id,payment_terms,balance_due,amount_due,amount_paid,status,financial_status&service_request_id=eq.${requestId}`),
    serviceRows(`loan_signing_exceptions?select=*&loan_signing_assignment_id=eq.${id}&order=created_at.desc`),
    serviceRows(`loan_signing_visits?select=*&loan_signing_assignment_id=eq.${id}&order=visit_number`),
    serviceRows(`loan_signing_additional_charges?select=*&loan_signing_assignment_id=eq.${id}&order=created_at.desc`),
    serviceRows(`loan_signing_financial_resolutions?select=*&loan_signing_assignment_id=eq.${id}&order=created_at.desc`),
    assignment.organization_id?serviceRows(`loan_signing_organization_terms?select=*,loan_signing_policy_versions(version,configuration)&organization_id=eq.${assignment.organization_id}&policy_key=eq.lsa_operational_policy&retired_at=is.null&order=effective_at.desc&limit=1`):Promise.resolve([]),
  ]);
  const paymentTerms=assignment.payment_terms||"prepaid"; const prepaidBalance=invoices.filter((i:any)=>String(i.payment_terms||paymentTerms)==="prepaid"&&!['void','cancelled'].includes(i.status)).reduce((sum:number,i:any)=>sum+Math.max(0,Number(i.balance_due??(Number(i.amount_due||0)-Number(i.amount_paid||0)))),0);
  const financials={original_agreed_fee:Number(assignment["agreed"+"_fee"]||0),previously_invoiced:invoices.reduce((s:number,i:any)=>s+Number(i.amount_due||0),0),previously_paid:invoices.reduce((s:number,i:any)=>s+Number(i.amount_paid||0),0)};
  const organizationTerm=organizationTerms[0] as any; const policy=policyMerge(DEFAULT_LSA_POLICY,{...(organizationTerm?.loan_signing_policy_versions?.configuration||{}),...(organizationTerm?.terms||{}),version:organizationTerm?.loan_signing_policy_versions?.version||DEFAULT_LSA_POLICY.version,source:organizationTerm?"organization_contract":"default_aps_policy",policy_version_id:organizationTerm?.policy_version_id||null});
  return {assignment,requirements,packages,stipulations,scanbacks,returns,invoices,exceptions,visits,charges,resolutions,financials,policy,completion:loanSigningCompletion({assignment,requirements,packages,stipulations,scanbacks,returns,payment_terms:paymentTerms,prepaid_balance:prepaidBalance})};
}
async function timeline(requestId:string,eventType:string,title:string,detail:string,adminId:string,metadata:Record<string,unknown>={}){await serviceRows("request_timeline_events",{method:"POST",body:JSON.stringify({service_request_id:requestId,event_type:eventType,title,detail,actor_type:"admin",visibility:"internal",metadata:{...metadata,admin_id:adminId}})});}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
  const admin=await requireRelease2Staff(req); if(!allowedRoles.has(String(admin.profile.role)))throw new Error("Operations or administrator access is required.");
  const body=await req.json() as Record<string,unknown>; const requestId=uuid(body.request_id); if(!requestId)throw new Error("Request is required.");
  const base=await snapshot(requestId); const assignment=base.assignment as Record<string,unknown>; const command=String(body.command||"snapshot"); if(command==="snapshot")return json({ok:true,...base});
  if(!operationalRoles.has(String(admin.profile.role))&&!financialRoles.has(String(admin.profile.role)))throw new Error("Read-only staff cannot modify Loan Signing records.");
  const financialCommand=["resolve_financial","execute_charge_invoice"].includes(command)||(command==="save_charge"&&body.decision==="authorized");
  if(financialCommand&&!financialRoles.has(String(admin.profile.role)))throw new Error("Billing or administrator access is required for financial review.");
  if(financialCommand&&!mayApproveFinancial(admin.profile))throw new Error("Loan Signing financial approval permission is required.");
  if(command==="save_assignment"){
    const update=pick(body,fields.assignment); if(body.instructions_reviewed===true){update.instructions_reviewed_at=new Date().toISOString();update.instructions_reviewed_by=admin.id;}
    if(Object.hasOwn(update,"round_trip_miles")){
      const miles=Number(update.round_trip_miles);if(!Number.isFinite(miles)||miles<0)throw new Error("Round-trip mileage must be zero or greater.");
      update.round_trip_miles=miles;
      update.travel_adjustment=miles>=31&&miles<=40?25:0;
      update.pricing_review_required=miles>40||["commercial","other_custom"].includes(String(assignment.signing_type));
      update.pricing_review_reason=miles>40?"Loan Signing travel above 40 round-trip miles requires operator review.":["commercial","other_custom"].includes(String(assignment.signing_type))?"Commercial, custom, or unusual assignment pricing requires operator review.":null;
    }
    const active=(base.packages as any[]).find((p)=>p.status==="active"); Object.assign(update,expectedPrintVolume(active,{...assignment,...update}));
    await serviceRows(`loan_signing_assignments?id=eq.${assignment.id}`,{method:"PATCH",body:JSON.stringify({...update,updated_at:new Date().toISOString()})});
    await timeline(requestId,"lsa_assignment_requirements_updated","Loan Signing requirements updated","Assignment requirements and preparation state were updated.",admin.id); return json({ok:true,...await snapshot(requestId)});
  }
  if(command==="add_package"){
    const requestedFileId=uuid(body.source_file_id); const files=await serviceRows(`request_files?select=id,detected_page_count,page_count_status,page_count_source,file_name&service_request_id=eq.${requestId}&is_active=eq.true${requestedFileId?`&id=eq.${requestedFileId}`:"&document_classification=in.(lsa_signing_package_source,lsa_redraw_correction)"}&order=created_at.desc&limit=1`); const sourceFile=files[0];
    const count=Number(sourceFile?.detected_page_count); if(!sourceFile||!Number.isInteger(count)||count<1||!["detected","manual"].includes(String(sourceFile.page_count_status)))throw new Error("Select an active package source with a server-counted or administrator-verified authoritative page count.");
    const prior=(base.packages as any[]).find((p)=>p.status==="active"); if(prior)await serviceRows(`loan_signing_package_versions?id=eq.${prior.id}`,{method:"PATCH",body:JSON.stringify({status:"superseded",superseded_at:new Date().toISOString()})});
    const version=Math.max(0,...(base.packages as any[]).map((p)=>Number(p.version_number)))+1; const pricingImpact=Boolean(prior&&Number(prior.authoritative_page_count)!==count);
    await serviceRows("loan_signing_package_versions",{method:"POST",body:JSON.stringify({loan_signing_assignment_id:assignment.id,service_request_id:requestId,organization_id:assignment.organization_id||null,version_number:version,source_file_id:sourceFile.id,authoritative_page_count:count,letter_page_count:body.letter_page_count??null,legal_page_count:body.legal_page_count??null,replacement_reason:String(body.replacement_reason||"").slice(0,1000)||null,dependent_review_required:Boolean(prior),pricing_impact_review:pricingImpact,created_by:admin.id})});
    if(prior)await serviceRows(`loan_signing_assignments?id=eq.${assignment.id}`,{method:"PATCH",body:JSON.stringify({package_status:"replacement_received",scope_review_required:true,print_qc_status:"pending",borrower_copy_status:assignment.borrower_copy_required==="yes"?"pending":assignment.borrower_copy_status,updated_at:new Date().toISOString()})});
    await timeline(requestId,prior?"lsa_replacement_package_received":"lsa_package_received",prior?"Replacement package received":"Package received",`Package version ${version} recorded from ${sourceFile.file_name} with ${count} authoritative pages.`,admin.id,{source_file_id:sourceFile.id,page_count_source:sourceFile.page_count_source,prior_version:prior?.version_number||null,new_version:version,prior_page_count:prior?.authoritative_page_count||null,new_page_count:count,pricing_impact_review:pricingImpact}); return json({ok:true,...await snapshot(requestId)});
  }
  if(["save_requirement","save_stipulation","save_scanback","save_return"].includes(command)){
    const kind=command.replace("save_","") as keyof typeof tables; const table=tables[kind]; const id=uuid(body.id); const payload={...pick(body,(fields as Record<string,string[]>)[kind]||[]),loan_signing_assignment_id:assignment.id,service_request_id:requestId,organization_id:assignment.organization_id||null};
    if(id)await serviceRows(`${table}?id=eq.${id}&loan_signing_assignment_id=eq.${assignment.id}`,{method:"PATCH",body:JSON.stringify({...payload,updated_at:new Date().toISOString()})}); else await serviceRows(table,{method:"POST",body:JSON.stringify({...payload,created_by:admin.id})});
    await timeline(requestId,`lsa_${kind}_updated`,`Loan Signing ${kind} updated`,"A consequential fulfillment record was updated.",admin.id); return json({ok:true,...await snapshot(requestId)});
  }
  if(command==="save_exception"){
    const outcome=String(body.outcome||""); const allowed=new Set(["cancelled","no_sign","partial_incomplete","resign_required","return_visit_required","excessive_wait_review","package_document_issue","signer_unavailable","identity_notarization_stop","orderer_instruction_stop","other_review"]); if(!allowed.has(outcome))throw new Error("Select a valid Loan Signing exception outcome.");
    const latestVisit=(base.visits as any[]).at(-1)||{}; const facts={print_status:assignment.print_status,travel_started_at:body.travel_started_at||latestVisit.travel_started_at||null,arrival_at:assignment.arrival_at||latestVisit.arrival_at,signing_started_at:assignment.signing_started_at||latestVisit.signing_started_at,signing_ended_at:assignment.signing_ended_at||latestVisit.signing_ended_at,departure_at:assignment.departure_at||latestVisit.departure_at};
    const policySource=String(body.policy_source||base.policy.source||"default_aps_policy"); const permittedSources=new Set(["default_aps_policy","organization_contract","assignment_specific_agreement","manual_authorized_exception"]); if(!permittedSources.has(policySource))throw new Error("Select a valid policy source.");
    const open=(base.exceptions as any[]).find(item=>item.outcome===outcome&&!['resolved','closed'].includes(item.status));if(open)return json({ok:true,reused:true,...await snapshot(requestId)});
    const policy=policyMerge(base.policy,typeof body.policy_override==="object"&&body.policy_override?body.policy_override:{}); const suggestion=outcome==="cancelled"?suggestedCancellationCharge({agreedFee:Number(assignment["agreed"+"_fee"]||0),facts,policy}):outcome==="excessive_wait_review"?waitReview({...facts,aps_caused_delay:Boolean(body.aps_caused_delay),policy}):outcome==="resign_required"?resignReview({agreedFee:Number(assignment["agreed"+"_fee"]||0),cause:String(body.cause_category||"unknown_review")}):null;
    const payload={loan_signing_assignment_id:assignment.id,service_request_id:requestId,organization_id:assignment.organization_id||null,outcome,status:"review_required",requested_by_type:body.requested_by_type||null,requested_at:body.requested_at||new Date().toISOString(),reason_code:String(body.reason_code||"other_review"),directed_by:String(body.directed_by||"").slice(0,300)||null,neutral_internal_note:String(body.neutral_internal_note||"").slice(0,3000)||null,lsa_stage_snapshot:assignment.lsa_stage,operational_facts:facts,policy_source:policySource,policy_version_id:uuid(policy.policy_version_id)||null,policy_snapshot:{...policy,suggestion},cause_category:body.cause_category||"unknown_review",customer_safe_status:customerSafeException(outcome),communication_state:"needed",idempotency_key:String(body.idempotency_key||"").slice(0,180)||null,created_by:admin.id};
    const created=await serviceRows("loan_signing_exceptions?select=*",{method:"POST",body:JSON.stringify(payload),headers:{Prefer:"return=representation"}}); const exception=created[0];
    await serviceRows(`loan_signing_assignments?id=eq.${assignment.id}`,{method:"PATCH",body:JSON.stringify({exception_attention_state:outcome,exception_financial_state:"review_required",updated_at:new Date().toISOString()})});
    const blockerKey=`lsa_${outcome}_review`; await serviceRows("review_queue_items",{method:"POST",body:JSON.stringify({service_request_id:requestId,blocker_key:blockerKey,title:customerSafeException(outcome),detail:"Loan Signing exception requires operational, financial, and communication review.",target_tab:"fulfillment",source_object_type:"loan_signing_exception",source_object_id:exception.id})});
    await timeline(requestId,"lsa_exception_recorded","Loan Signing exception recorded",`Outcome ${outcome} requires administrator review; no financial action was automatic.`,admin.id,{exception_id:exception.id,suggestion}); return json({ok:true,...await snapshot(requestId)});
  }
  if(command==="save_visit"){
    const number=Math.max(0,...(base.visits as any[]).map(v=>Number(v.visit_number)))+1; await serviceRows("loan_signing_visits",{method:"POST",body:JSON.stringify({loan_signing_assignment_id:assignment.id,service_request_id:requestId,exception_id:uuid(body.exception_id)||null,visit_number:number,visit_type:body.visit_type||"return_visit",appointment_at:body.appointment_at||null,travel_started_at:body.travel_started_at||null,arrival_at:body.arrival_at||null,signing_started_at:body.signing_started_at||null,signing_ended_at:body.signing_ended_at||null,departure_at:body.departure_at||null,outcome:body.outcome||null,created_by:admin.id})}); await timeline(requestId,"lsa_visit_added",`Loan Signing visit ${number} added`,`A linked ${body.visit_type||"return visit"} was added without creating a duplicate assignment.`,admin.id); return json({ok:true,...await snapshot(requestId)});
  }
  if(command==="save_charge"){
    const chargeTypes=new Set(["excessive_wait","additional_authorized_travel","authorized_reprint","replacement_package_preparation","additional_signing_visit","resign_fee","cancellation_charge","other_authorized_assignment_adjustment"]),decision=String(body.decision||"pending_review");if(!chargeTypes.has(String(body.charge_type))||!["pending_review","waived","authorized"].includes(decision))throw new Error("Select a valid controlled charge type and decision.");const suggested=Math.max(0,Number(body.suggested_amount||0)),authorized=decision==="authorized",authorizedAmount=authorized?Math.max(0,Number(body.authorized_amount||0)):null;if(authorized&&authorizedAmount===null)throw new Error("Authorized amount is required.");const idempotency=String(body.idempotency_key||"").slice(0,180)||null;if(idempotency&&(base.charges as any[]).some(item=>item.idempotency_key===idempotency))return json({ok:true,reused:true,...base}); await serviceRows("loan_signing_additional_charges",{method:"POST",body:JSON.stringify({loan_signing_assignment_id:assignment.id,service_request_id:requestId,organization_id:assignment.organization_id||null,exception_id:uuid(body.exception_id)||null,charge_type:body.charge_type,suggested_amount:suggested,authorized_amount:authorizedAmount,decision,reason:String(body.reason||"").slice(0,2000)||null,customer_safe_explanation:String(body.customer_safe_explanation||"").slice(0,2000)||null,authorized_by:authorized?admin.id:null,authorized_at:authorized?new Date().toISOString():null,communication_state:authorized?"needed":"not_required",policy_source:base.policy.source||"default_aps_policy",policy_snapshot:base.policy,idempotency_key:idempotency})}); await timeline(requestId,"lsa_charge_reviewed","Loan Signing charge reviewed",authorized?"An additional charge was authorized for separate invoice handling.":"A suggested charge was recorded for review or waived; no invoice was created.",admin.id); return json({ok:true,...await snapshot(requestId)});
  }
  if(command==="resolve_financial"){
    const exceptionId=uuid(body.exception_id); if(!exceptionId)throw new Error("Exception is required."); const values=["no_charge","partial_charge","full_agreed_fee","custom_authorized_amount","full_refund","partial_refund","no_refund","no_financial_change"]; if(!values.includes(String(body.resolution_type)))throw new Error("Select a valid financial resolution.");
    const exception=(base.exceptions as any[]).find(item=>item.id===exceptionId);if(!exception)throw new Error("Exception does not belong to this assignment.");if((base.resolutions as any[]).some(item=>item.exception_id===exceptionId))return json({ok:true,reused:true,...base});const reason=String(body.decision_reason||"").trim();if(!reason)throw new Error("Internal decision rationale is required.");const authorizedCharge=Math.max(0,Number(body.authorized_charge||0)),authorizedAdditional=(base.charges as any[]).filter(item=>item.exception_id===exceptionId&&item.decision==="authorized"&&item.charge_type!=="cancellation_charge").reduce((sum,item)=>sum+Number(item.authorized_amount||0),0),preview=financialResolutionPreview({originalAgreedFee:base.financials.original_agreed_fee,previouslyInvoiced:base.financials.previously_invoiced,previouslyPaid:base.financials.previously_paid,authorizedCharge,authorizedAdditionalCharges:authorizedAdditional});const idempotency=`lsa-resolution:${exceptionId}`;
    if(preview.refund_due>0&&admin.profile.role!=="owner"&&admin.profile.permissions?.issue_refunds!==true)throw new Error("Refund permission is required for a resolution that creates a refund review.");const created=await serviceRows("loan_signing_financial_resolutions?select=*",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({loan_signing_assignment_id:assignment.id,service_request_id:requestId,exception_id:exceptionId,resolution_type:body.resolution_type,...preview,authorized_charge:authorizedCharge,additional_amount_due:preview.additional_amount_due,refund_due:preview.refund_due,net_retained:preview.net_retained,decision_reason:reason.slice(0,3000),customer_safe_explanation:String(body.customer_safe_explanation||"").slice(0,2000)||null,decision_by:admin.id,policy_source:exception.policy_source,policy_snapshot:exception.policy_snapshot,idempotency_key:idempotency,resolution_state:preview.refund_due>0?"refund_pending":preview.additional_amount_due>0?"invoice_pending":"communication_pending"})});const resolution=created[0];if(preview.refund_due>0)await serviceRows("refund_reviews",{method:"POST",body:JSON.stringify({service_request_id:requestId,loan_signing_resolution_id:resolution.id,status:"approved",requested_amount:preview.refund_due,approved_amount:preview.refund_due,admin_note:`Loan Signing exception ${exceptionId}: ${reason.slice(0,900)}`})});
    await serviceRows(`loan_signing_exceptions?id=eq.${exceptionId}&loan_signing_assignment_id=eq.${assignment.id}`,{method:"PATCH",body:JSON.stringify({status:"communication_needed",communication_state:"needed",customer_safe_explanation:body.customer_safe_explanation||null,resolved_by:admin.id,resolved_at:new Date().toISOString(),updated_at:new Date().toISOString()})});await serviceRows(`loan_signing_assignments?id=eq.${assignment.id}`,{method:"PATCH",body:JSON.stringify({exception_financial_state:preview.refund_due>0?"refund_due":preview.additional_amount_due>0?"additional_amount_due":"communication_needed",authorized_refund_due:preview.refund_due,authorized_additional_amount_due:preview.additional_amount_due,updated_at:new Date().toISOString()})}); await serviceRows(`review_queue_items?source_object_id=eq.${exceptionId}&state=eq.open`,{method:"PATCH",body:JSON.stringify({state:"resolved",resolved_at:new Date().toISOString(),resolved_by:admin.id,updated_at:new Date().toISOString()})});if(preview.refund_due>0)await serviceRows("review_queue_items",{method:"POST",body:JSON.stringify({service_request_id:requestId,blocker_key:"lsa_refund_due",title:"Loan Signing Refund Due",detail:"An authorized refund review requires processing through the existing APS refund workflow.",target_tab:"quote-payment",source_object_type:"loan_signing_financial_resolution",source_object_id:resolution.id})});if(preview.additional_amount_due>0)await serviceRows("review_queue_items",{method:"POST",body:JSON.stringify({service_request_id:requestId,blocker_key:"lsa_additional_amount_due",title:"Loan Signing Additional Amount Due",detail:"An authorized amount requires a separate supplemental invoice.",target_tab:"quote-payment",source_object_type:"loan_signing_financial_resolution",source_object_id:resolution.id})});await timeline(requestId,"lsa_financial_resolution_authorized","Loan Signing financial resolution authorized","An administrator authorized the exception financial result; invoice/refund execution remains in the existing APS financial workflow.",admin.id,{exception_id:exceptionId,resolution_id:resolution.id,resolution_type:body.resolution_type,refund_due:preview.refund_due,additional_amount_due:preview.additional_amount_due,final_service_value:preview.final_service_value}); return json({ok:true,preview,...await snapshot(requestId)});
  }
  if(command==="execute_charge_invoice"){
    const resolutionId=uuid(body.resolution_id),resolution=(base.resolutions as any[]).find(item=>item.id===resolutionId);if(!resolution)throw new Error("Financial resolution is required.");if(resolution.invoice_id)return json({ok:true,reused:true,...base});const billable=(base.charges as any[]).filter(item=>item.decision==="authorized"&&!item.invoice_id&&(!item.exception_id||item.exception_id===resolution.exception_id));const resolutionAmount=Math.max(0,Number(resolution.additional_amount_due||0));if(resolutionAmount<=0&&!billable.length)throw new Error("No authorized additional amount is ready for invoicing.");const items=billable.length?billable.map(item=>({item_type:`lsa_${item.charge_type}`,description:item.customer_safe_explanation||String(item.charge_type).replaceAll("_"," "),quantity:1,unit_price:Number(item.authorized_amount||0),line_total:Number(item.authorized_amount||0)})):[{item_type:"lsa_authorized_adjustment",description:resolution.customer_safe_explanation||"Authorized Loan Signing adjustment",quantity:1,unit_price:resolutionAmount,line_total:resolutionAmount}];const invoiceResponse=await fetch(`${Deno.env.get("SUPABASE_URL")}/functions/v1/create-additional-invoice`,{method:"POST",headers:{Authorization:req.headers.get("Authorization")||"","Content-Type":"application/json"},body:JSON.stringify({request_id:requestId,note:"Authorized Loan Signing exception adjustment.",items})}),invoiceData=await invoiceResponse.json().catch(()=>({}));if(!invoiceResponse.ok||!invoiceData?.ok)throw new Error(invoiceData?.error||"Supplemental invoice could not be created.");await serviceRows(`loan_signing_financial_resolutions?id=eq.${resolutionId}`,{method:"PATCH",body:JSON.stringify({invoice_id:invoiceData.invoice.id,resolution_state:"communication_pending",updated_at:new Date().toISOString()})});for(const item of billable)await serviceRows(`loan_signing_additional_charges?id=eq.${item.id}`,{method:"PATCH",body:JSON.stringify({invoice_id:invoiceData.invoice.id,decision:"invoiced",updated_at:new Date().toISOString()})});await serviceRows(`review_queue_items?source_object_id=eq.${resolutionId}&blocker_key=eq.lsa_additional_amount_due&state=eq.open`,{method:"PATCH",body:JSON.stringify({state:"resolved",resolved_at:new Date().toISOString(),resolved_by:admin.id,updated_at:new Date().toISOString()})});await timeline(requestId,"lsa_additional_charge_invoiced","Loan Signing additional charge invoiced","The authorized amount was placed on a separate supplemental invoice without changing the original assignment invoice.",admin.id,{resolution_id:resolutionId,invoice_id:invoiceData.invoice.id});return json({ok:true,invoice:invoiceData.invoice,...await snapshot(requestId)});
  }
  if(command==="close_exception"){
    if(!operationalRoles.has(String(admin.profile.role)))throw new Error("Operations or administrator access is required to close an exception.");
    const exceptionId=uuid(body.exception_id),exception=(base.exceptions as any[]).find(item=>item.id===exceptionId);if(!exception)throw new Error("Exception does not belong to this assignment.");if(["resolved","closed"].includes(exception.status))return json({ok:true,reused:true,...base});
    const resolution=(base.resolutions as any[]).find(item=>item.exception_id===exceptionId);if(!resolution)throw new Error("Authorize the financial outcome before closing the exception.");
    const openFinancial=await serviceRows(`review_queue_items?select=id&source_object_id=eq.${resolution.id}&state=eq.open&blocker_key=in.(lsa_refund_due,lsa_additional_amount_due)&limit=1`);if(openFinancial.length)throw new Error("Complete the existing refund or supplemental-invoice review before closing the exception.");
    if(body.communication_complete!==true)throw new Error("Confirm that the customer-safe resolution communication is complete.");const now=new Date().toISOString();
    await serviceRows(`loan_signing_exceptions?id=eq.${exceptionId}&loan_signing_assignment_id=eq.${assignment.id}`,{method:"PATCH",body:JSON.stringify({status:"closed",communication_state:"sent",closed_at:now,updated_at:now})});await serviceRows(`loan_signing_financial_resolutions?id=eq.${resolution.id}`,{method:"PATCH",body:JSON.stringify({resolution_state:"resolved",updated_at:now})});
    const otherOpen=(base.exceptions as any[]).some(item=>item.id!==exceptionId&&!["resolved","closed"].includes(item.status));await serviceRows(`loan_signing_assignments?id=eq.${assignment.id}`,{method:"PATCH",body:JSON.stringify({exception_attention_state:otherOpen?assignment.exception_attention_state:null,exception_financial_state:otherOpen?assignment.exception_financial_state:"resolved",authorized_refund_due:otherOpen?assignment.authorized_refund_due:0,authorized_additional_amount_due:otherOpen?assignment.authorized_additional_amount_due:0,updated_at:now})});
    await timeline(requestId,"lsa_exception_closed","Loan Signing exception closed","Financial follow-up and customer-safe resolution communication were completed before the exception was closed.",admin.id,{exception_id:exceptionId,resolution_id:resolution.id});return json({ok:true,...await snapshot(requestId)});
  }
  if(command==="evaluate_completion")return json({ok:true,...await snapshot(requestId)});
  throw new Error("Unsupported command.");
}catch(error){return json({ok:false,error:error instanceof Error?error.message:"Request failed."},400);}});
