const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "https://sfsdniavqldgbiretply.supabase.co";
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") || "";
const SITE_URL = Deno.env.get("SITE_URL") || "https://alignedprintscan.com";
const FROM_EMAIL = Deno.env.get("FROM_EMAIL") || "Aligned Print & Scan <hello@alignedprintscan.com>";
const SUPPORT_EMAIL = Deno.env.get("SUPPORT_EMAIL") || "hello@alignedprintscan.com";
const SUPPORT_PHONE = Deno.env.get("SUPPORT_PHONE") || "(469) 383-8879";
const LOGO_URL = Deno.env.get("EMAIL_LOGO_URL") || `${SITE_URL}/assets/images/logo-full.webp`;
function json(body: unknown, status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}})}
function esc(v: unknown){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]||c))}
function money(v: unknown){return `$${Number(v||0).toFixed(2)}`}
function refFromId(id:string){return id?"APS-"+id.slice(0,8).toUpperCase():"APS-REQUEST"}
async function supabaseFetch(path: string, init: RequestInit = {}){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,"Content-Type":"application/json",Prefer:"return=representation",...(init.headers||{})}})}
function shell(body:string,preheader:string){return `<!doctype html><html><head><meta name="color-scheme" content="light only"><meta name="supported-color-schemes" content="light"></head><body style="margin:0;background:#f6f3ee;font-family:Arial,Helvetica,sans-serif;color:#2d2d2d;line-height:1.6"><div style="display:none;max-height:0;overflow:hidden">${esc(preheader)}</div><table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="background:#f6f3ee;padding:28px 12px"><tr><td align="center"><table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="max-width:680px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #e7dcc5"><tr><td style="background:#ffffff;padding:30px 34px 20px;text-align:center;border-bottom:4px solid #c8a96b"><img src="${LOGO_URL}" alt="Aligned Print & Scan" style="max-width:210px;margin:0 auto 14px;display:block"><div style="font-size:12px;letter-spacing:.18em;text-transform:uppercase;color:#161c4d;font-weight:800">Remote & Mobile Notary · Print, Scan & Document Support</div></td></tr><tr><td style="padding:34px;background:#ffffff;color:#2d2d2d">${body}</td></tr><tr><td style="padding:26px 34px;background:#fffaf2;border-top:1px solid #e7dcc5;color:#5b5a61;font-size:14px"><strong style="color:#161c4d">Need assistance?</strong><br>If you have additional questions, contact customer support and include your APS reference number.<br><br><a href="mailto:${SUPPORT_EMAIL}" style="color:#161c4d;font-weight:bold">${SUPPORT_EMAIL}</a><br>${SUPPORT_PHONE}<br>Waxahachie, Texas<br><br><a href="${SITE_URL}/support.html" style="color:#c8a96b;font-weight:bold">Customer Support</a><div style="margin-top:18px;color:#8a8072">Aligned Print & Scan LLC</div></td></tr></table></td></tr></table></body></html>`}
function itemTable(items:any[], total:number){if(!items?.length)return "";const rows=items.map(i=>`<tr><td style="padding:12px;border-bottom:1px solid #eee">${esc(i.description||"Service")}</td><td style="padding:12px;border-bottom:1px solid #eee;text-align:right">${esc(i.quantity||1)}</td><td style="padding:12px;border-bottom:1px solid #eee;text-align:right">${money(i.unit_price)}</td><td style="padding:12px;border-bottom:1px solid #eee;text-align:right"><strong>${money(i.line_total||(Number(i.quantity||1)*Number(i.unit_price||0)))}</strong></td></tr>`).join("");return `<table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border:1px solid #eee;border-radius:14px;overflow:hidden;margin:18px 0"><thead><tr style="background:#161c4d;color:#fff"><th align="left" style="padding:12px">Service Item</th><th align="right" style="padding:12px">Qty</th><th align="right" style="padding:12px">Rate</th><th align="right" style="padding:12px">Total</th></tr></thead><tbody>${rows}</tbody><tfoot><tr style="background:#fffaf2;color:#161c4d"><td colspan="3" style="padding:14px;text-align:right"><strong>Total</strong></td><td style="padding:14px;text-align:right"><strong>${money(total)}</strong></td></tr></tfoot></table>`}
function contentForStatus(status:string, request:any, ref:string, note:string, total:number){const statusUrl=`${SITE_URL}/success.html?request_id=${request.id}&ref=${encodeURIComponent(ref)}`;const service={ron:"Remote Online Notary",mobile:"Mobile Notary",print:"Print & Scan"}[request.service_type]||"Service Request";const baseBtn=`<p><a href="${statusUrl}" style="display:inline-block;background:#c8a96b;color:#111522;padding:14px 22px;border-radius:999px;text-decoration:none;font-weight:bold">View Updated Status</a></p>`;if(status==="payment_received")return {subject:`Payment received: ${ref}`,pre:`Payment received: ${ref}`,html:`<p style="letter-spacing:.16em;text-transform:uppercase;color:#c8a96b;font-weight:800;margin:0 0 10px">Payment Received</p><h1 style="font-family:Georgia,serif;color:#161c4d;margin:0 0 12px;font-size:32px">Your Payment Has Been Received</h1><p>Hello ${esc(request.customer_first||"there")},</p><p>Thank you. Your payment for <strong>${esc(ref)}</strong> has been received and your ${esc(service)} request is moving to appointment confirmation or fulfillment.</p><div style="background:#fffaf2;border:1px solid #e7dcc5;border-radius:16px;padding:18px;margin:18px 0"><strong style="color:#161c4d">Amount:</strong> ${money(total)}<br><strong style="color:#161c4d">Reference:</strong> ${esc(ref)}<br><strong style="color:#161c4d">Invoice:</strong> ${esc(request.invoice_number||"Pending")}</div>${note?`<p><strong>Note:</strong> ${esc(note)}</p>`:""}${baseBtn}`};
if(status==="appointment_confirmed")return {subject:`Appointment confirmed: ${ref}`,pre:`Appointment confirmed: ${ref}`,html:`<p style="letter-spacing:.16em;text-transform:uppercase;color:#c8a96b;font-weight:800;margin:0 0 10px">Appointment Confirmed</p><h1 style="font-family:Georgia,serif;color:#161c4d;margin:0 0 12px;font-size:32px">Your Appointment Is Confirmed</h1><p>Hello ${esc(request.customer_first||"there")},</p><p>Your ${esc(service)} request is confirmed. Please review your status page for the latest appointment details, preparation notes, and any service-specific next steps.</p>${note?`<div style="background:#fffaf2;border:1px solid #e7dcc5;border-radius:16px;padding:18px;margin:18px 0">${esc(note)}</div>`:""}${baseBtn}`};
if(status==="completed")return {subject:`Service completed: ${ref}`,pre:`Service completed: ${ref}`,html:`<p style="letter-spacing:.16em;text-transform:uppercase;color:#c8a96b;font-weight:800;margin:0 0 10px">Service Completed</p><h1 style="font-family:Georgia,serif;color:#161c4d;margin:0 0 12px;font-size:32px">Your Service Is Complete</h1><p>Hello ${esc(request.customer_first||"there")},</p><p>Thank you for choosing Aligned Print & Scan. Your request <strong>${esc(ref)}</strong> has been marked complete. Your confirmation and receipt details remain available on your status page.</p>${note?`<p><strong>Completion note:</strong> ${esc(note)}</p>`:""}${baseBtn}`};
return {subject:`Status update: ${ref}`,pre:`Status update: ${ref}`,html:`<p style="letter-spacing:.16em;text-transform:uppercase;color:#c8a96b;font-weight:800;margin:0 0 10px">Status Update</p><h1 style="font-family:Georgia,serif;color:#161c4d;margin:0 0 12px;font-size:32px">Your Request Has Been Updated</h1><p>Hello ${esc(request.customer_first||"there")},</p><p>Your ${esc(service)} request <strong>${esc(ref)}</strong> has been updated.</p>${note?`<p><strong>Update:</strong> ${esc(note)}</p>`:""}${baseBtn}`}}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});try{if(!RESEND_API_KEY)throw new Error("RESEND_API_KEY is not configured.");const {request_id,status="status_update",note=""}=await req.json();if(!request_id)throw new Error("Missing request_id.");const reqRes=await supabaseFetch(`service_requests?select=id,service_type,status,quote_amount,estimated_total,paid_amount,invoice_number,customers(first_name,last_name,email)&id=eq.${request_id}`);const rows=await reqRes.json();const request=rows?.[0];if(!request)throw new Error("Request not found.");const customer=Array.isArray(request.customers)?request.customers[0]:request.customers;if(!customer?.email)throw new Error("Customer email missing.");request.customer_first=customer.first_name||"there";const itemsRes=await supabaseFetch(`invoice_items?select=description,quantity,unit_price,line_total,item_type&service_request_id=eq.${request_id}&order=created_at.asc`);const items=itemsRes.ok?await itemsRes.json():[];const total=Number(request.paid_amount||request.quote_amount||request.estimated_total||0);const ref=refFromId(request_id);const content=contentForStatus(status,request,ref,String(note||""),total);const html=shell(`${content.html}${itemTable(items,total)}`,content.pre);const send=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:FROM_EMAIL,to:[customer.email],subject:content.subject,html})});const sent=await send.json();if(!send.ok)throw new Error(sent?.message||"Resend email failed.");await supabaseFetch(`request_status_updates`,{method:"POST",body:JSON.stringify({service_request_id:request_id,status,message:`Customer email sent: ${content.subject}`,sent_email:true,sent_sms:false})});return json({ok:true,id:sent.id});}catch(err){return json({ok:false,error:err instanceof Error?err.message:String(err)},400)}});
