import { addressText, completeAddress, drivingRoute, geocodeAddress, routeCacheKey, routeMetrics, selectTravelTier } from "../_shared/mobile-travel.mjs";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const URL=Deno.env.get("SUPABASE_URL")||"",SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",ORS_KEY=Deno.env.get("OPENROUTESERVICE_API_KEY")||Deno.env.get("ORS_API_KEY")||"";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const validId=(value:unknown)=>{const text=String(value||"").trim();return /^[0-9a-f-]{36}$/i.test(text)?text:""};
const money=(value:unknown)=>Math.round(Number(value||0)*100)/100;
async function rest(path:string,init:RequestInit={}){return fetch(`${URL}/rest/v1/${path}`,{...init,headers:{apikey:SERVICE,Authorization:`Bearer ${SERVICE}`,"Content-Type":"application/json",Prefer:"return=representation",...(init.headers||{})}})}
async function rows(path:string){const response=await rest(path);if(!response.ok)throw new Error(await response.text());return response.json()}
async function write(path:string,method:string,body:unknown){const response=await rest(path,{method,body:JSON.stringify(body)});if(!response.ok)throw new Error(await response.text());return response.json()}
async function requireAdmin(req:Request){const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))throw new Error("Administrator authentication is required.");const userResponse=await fetch(`${URL}/auth/v1/user`,{headers:{apikey:SERVICE,Authorization:auth}});if(!userResponse.ok)throw new Error("Administrator authentication is required.");const user=await userResponse.json();const check=await fetch(`${URL}/rest/v1/rpc/is_admin`,{method:"POST",headers:{apikey:SERVICE,Authorization:auth,"Content-Type":"application/json"},body:"{}"});if(!check.ok||await check.json()!==true)throw new Error("Administrator access is required.");return {user,auth}}
async function requestContext(requestId:string){const [requests,details,tiers,calculations]=await Promise.all([rows(`service_requests?select=id,service_type,current_quote_id,quote_amount,estimated_total,paid_amount,payment_status&id=eq.${requestId}&limit=1`),rows(`mobile_notary_requests?select=street_address,unit,city,state,zip,travel_miles,travel_fee&service_request_id=eq.${requestId}&limit=1`),rows("mobile_travel_pricing_tiers?select=*&active=eq.true&order=sort_order.asc"),rows(`mobile_travel_calculations?select=*&service_request_id=eq.${requestId}&order=calculated_at.desc&limit=10`)]);const request=requests[0];if(!request)throw new Error("Request not found.");if(request.service_type!=="mobile")throw new Error("Travel calculation is available only for Mobile Notary requests.");return {request,detail:details[0]||null,tiers,calculations}}
function originBody(value:any){const address=completeAddress(value);if(!address)throw new Error("Origin street, city, state, and ZIP are required.");const label=String(value.label||"").trim();if(label.length<2)throw new Error("An origin label is required.");return {label,...address,is_active:value.is_active!==false}}
async function origins(){return rows("travel_origins?select=*&order=is_default.desc,label.asc")}
async function ensureDefault(id:string,adminId:string){await write("travel_origins?is_default=eq.true","PATCH",{is_default:false,updated_by:adminId,updated_at:new Date().toISOString()});await write(`travel_origins?id=eq.${id}&is_active=eq.true`,"PATCH",{is_default:true,updated_by:adminId,updated_at:new Date().toISOString()})}
async function timeline(requestId:string,calculation:any,fee:number,adminId:string){await write("request_timeline_events","POST",{service_request_id:requestId,event_type:"mobile_travel_applied",title:"Mobile travel calculated",detail:`${Number(calculation.round_trip_miles).toFixed(1)} round-trip miles · ${calculation.pricing_tier_label} · $${fee.toFixed(2)} travel fee applied to quote`,actor_type:"admin",visibility:"internal",metadata:{calculation_id:calculation.id,pricing_tier_key:calculation.pricing_tier_key,suggested_fee:calculation.suggested_fee,applied_fee:fee,admin_id:adminId}})}
async function applyDraft(context:any,calculation:any,fee:number,note:string,adminId:string){const request=context.request,quoteRows=request.current_quote_id?await rows(`quotes?select=*&id=eq.${request.current_quote_id}&limit=1`):await rows(`quotes?select=*&service_request_id=eq.${request.id}&order=version.desc&limit=1`),quote=quoteRows[0]||null;if(quote&&["sent","approved"].includes(String(quote.state)))throw new Error("This quote has already been sent or approved. Use the maintained quote revision/reissue workflow; APS will not silently change it.");const existing=(await rows(`invoice_items?select=*&service_request_id=eq.${request.id}&invoice_id=is.null&item_type=eq.mobile_travel&limit=1`))[0];const item={service_request_id:request.id,invoice_id:null,item_type:"mobile_travel",description:`Mobile Travel — ${calculation.pricing_tier_label}`,quantity:1,unit_price:fee,line_total:fee,taxable:false};let itemRow;if(existing)itemRow=(await write(`invoice_items?id=eq.${existing.id}`,"PATCH",item))[0];else itemRow=(await write("invoice_items","POST",item))[0];const otherItems=await rows(`invoice_items?select=line_total&service_request_id=eq.${request.id}&invoice_id=is.null`),total=money(otherItems.reduce((sum:number,row:any)=>sum+Number(row.line_total||0),0));let quoteId=quote?.id||null;if(quoteId)await write(`quotes?id=eq.${quoteId}`,"PATCH",{amount:total,state:"saved",updated_by:adminId,updated_at:new Date().toISOString()});else{const created=await write("quotes","POST",{service_request_id:request.id,quote_number:`Q-${request.id.slice(0,8).toUpperCase()}-01`,state:"saved",amount:total,notes:"",version:1,created_by:adminId,updated_by:adminId});quoteId=created[0].id}await write(`service_requests?id=eq.${request.id}`,"PATCH",{current_quote_id:quoteId,quote_amount:total,full_quote_amount:total,initial_payment_amount:total});await write(`mobile_notary_requests?service_request_id=eq.${request.id}`,"PATCH",{travel_miles:calculation.round_trip_miles,travel_fee:fee});return {quote_id:quoteId,invoice_item_id:itemRow.id,total,note}}
async function applyPaid(req:Request,context:any,calculation:any,fee:number,note:string){const response=await fetch(`${URL}/functions/v1/create-additional-invoice`,{method:"POST",headers:{Authorization:req.headers.get("Authorization")||"","Content-Type":"application/json"},body:JSON.stringify({request_id:context.request.id,note:note||"Approved Mobile travel adjustment.",items:[{item_type:"mobile_travel",description:`Mobile Travel — ${calculation.pricing_tier_label}`,quantity:1,unit_price:fee,line_total:fee}]})});const payload=await response.json().catch(()=>({}));if(!response.ok||payload?.ok===false)throw new Error(payload?.error||"The supplemental travel invoice could not be created.");return {quote_id:context.request.current_quote_id||null,invoice_item_id:payload?.invoice_item_ids?.[0]||null,supplemental:true}}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const {user,auth}=await requireAdmin(req),body=await req.json(),command=String(body.command||"");
 if(command==="list_origins")return json({ok:true,origins:await origins(),configured:Boolean(ORS_KEY)});
 if(command==="save_origin"){const values=originBody(body.origin||body),originId=validId(body.origin_id);let saved;if(originId)saved=(await write(`travel_origins?id=eq.${originId}`,"PATCH",{...values,updated_by:user.id,updated_at:new Date().toISOString()}))[0];else saved=(await write("travel_origins","POST",{...values,created_by:user.id,updated_by:user.id}))[0];const active=await origins();if(body.is_default||!active.some((row:any)=>row.is_active&&row.is_default))await ensureDefault(saved.id,user.id);return json({ok:true,origins:await origins()});}
 if(command==="set_default"){const originId=validId(body.origin_id);if(!originId)throw new Error("Choose a saved active origin.");await ensureDefault(originId,user.id);return json({ok:true,origins:await origins()});}
 if(command==="deactivate_origin"){const originId=validId(body.origin_id);if(!originId)throw new Error("Choose an origin.");await write(`travel_origins?id=eq.${originId}`,"PATCH",{is_active:false,is_default:false,updated_by:user.id,updated_at:new Date().toISOString()});const active=(await origins()).filter((row:any)=>row.is_active);if(active.length&&!active.some((row:any)=>row.is_default))await ensureDefault(active[0].id,user.id);return json({ok:true,origins:await origins()});}
 const requestId=validId(body.request_id);if(!requestId)throw new Error("A valid Mobile request is required.");const context=await requestContext(requestId);
 if(command==="get_request")return json({ok:true,...context,origins:(await origins()).filter((row:any)=>row.is_active),configured:Boolean(ORS_KEY)});
 if(command==="calculate"){const destination=completeAddress(context.detail||{});if(!destination)throw new Error("Travel distance unavailable — complete the Mobile service address first.");let originId=validId(body.origin_id),originLabel="One-time origin",origin;if(body.one_time_origin){origin=completeAddress(body.one_time_origin);if(!origin)throw new Error("Complete the one-time starting address first.");originLabel=String(body.one_time_origin.label||originLabel).trim();originId=""}else{const available=await origins(),selected=available.find((row:any)=>row.id===originId&&row.is_active)||available.find((row:any)=>row.is_active&&row.is_default);if(!selected)throw new Error("Add an active Default Travel Origin in Settings or use a one-time starting address.");origin=completeAddress(selected);originId=selected.id;originLabel=selected.label}const cacheKey=await routeCacheKey(origin,destination);if(!body.force){const cached=context.calculations.find((row:any)=>row.cache_key===cacheKey);if(cached)return json({ok:true,calculation:cached,cached:true,configured:Boolean(ORS_KEY)})}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);let metrics;try{const start=await geocodeAddress(origin,{apiKey:ORS_KEY,signal:controller.signal}),end=await geocodeAddress(destination,{apiKey:ORS_KEY,signal:controller.signal});metrics=await drivingRoute(start,end,{apiKey:ORS_KEY,signal:controller.signal})}catch(error){if(error instanceof DOMException&&error.name==="AbortError")throw new Error("Automatic travel calculation timed out. Enter the mileage/travel charge manually or try again.");throw error}finally{clearTimeout(timer)}const tier=selectTravelTier(metrics.round_trip_miles,context.tiers);if(!tier)throw new Error("No APS travel pricing tier matched this route. Enter the travel charge manually.");const calculation=(await write("mobile_travel_calculations","POST",{service_request_id:requestId,origin_id:originId||null,origin_label:originLabel,origin_address:origin,destination_address:addressText(destination),cache_key:cacheKey,...metrics,pricing_tier_key:tier.tier_key,pricing_tier_label:tier.label,suggested_fee:tier.fee,calculated_by:user.id}))[0];return json({ok:true,calculation,configured:Boolean(ORS_KEY)});}
 if(command==="apply_manual"){const fee=money(body.actual_fee),miles=Number(body.round_trip_miles||0),note=String(body.operator_note||"").trim();if(fee<0||!note)throw new Error("A non-negative travel fee and operator reason are required for manual fallback.");const tier=selectTravelTier(miles,context.tiers)||context.tiers.at(-1);const calculation=(await write("mobile_travel_calculations","POST",{service_request_id:requestId,origin_id:null,origin_label:"Manual operator entry",origin_address:{private:true},destination_address:addressText(context.detail||{}),cache_key:`manual:${crypto.randomUUID()}`,distance_meters:miles*1609.344/2,duration_seconds:0,one_way_miles:miles/2,round_trip_miles:miles,pricing_tier_key:tier.tier_key,pricing_tier_label:tier.label,suggested_fee:tier.fee,operator_note:note,calculated_by:user.id}))[0];body.calculation_id=calculation.id;body.actual_fee=fee;}
 if(command==="apply_to_quote"||command==="apply_manual"){const calculationId=validId(body.calculation_id),calculation=context.calculations.find((row:any)=>row.id===calculationId)||(await rows(`mobile_travel_calculations?select=*&id=eq.${calculationId}&service_request_id=eq.${requestId}&limit=1`))[0];if(!calculation)throw new Error("Calculate the route before applying a travel charge.");if(calculation.application_state==="applied")return json({ok:true,duplicate:true,calculation});const fee=money(body.actual_fee??calculation.suggested_fee),note=String(body.operator_note||"").trim();if(fee<0)throw new Error("Travel fee cannot be negative.");if(fee!==money(calculation.suggested_fee)&&!note)throw new Error("Explain why the applied fee differs from the APS suggestion.");const paid=Number(context.request.paid_amount||0)>0||["paid","payment_received","final_payment_received"].includes(String(context.request.payment_status||"").toLowerCase()),result=paid?await applyPaid(req,context,calculation,fee,note):await applyDraft(context,calculation,fee,note,user.id);await write(`mobile_travel_calculations?service_request_id=eq.${requestId}&application_state=eq.applied`,"PATCH",{application_state:"superseded"});await write(`mobile_travel_calculations?id=eq.${calculation.id}`,"PATCH",{application_state:"applied",applied_fee:fee,operator_note:note||null,quote_id:result.quote_id,invoice_item_id:result.invoice_item_id,applied_by:user.id,applied_at:new Date().toISOString()});await timeline(requestId,calculation,fee,user.id);return json({ok:true,calculation_id:calculation.id,applied_fee:fee,...result});}
 throw new Error("Unsupported travel command.");
 }catch(error){console.error("admin-route-distance",error);return json({ok:false,error:error instanceof Error?error.message:String(error)},400)}});
