const U=Deno.env.get("SUPABASE_URL")||"",K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",SALT=Deno.env.get("RESOURCE_RATE_LIMIT_SALT")||"aps-resource-v1";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json","cache-control":"no-store"}});
const clean=(v:unknown,max=500)=>String(v||"").trim().slice(0,max),slug=(v:unknown)=>/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(clean(v,160))?clean(v,160):"";
async function rows(path:string,init:RequestInit={}){const r=await fetch(`${U}/rest/v1/${path}`,{...init,headers:{apikey:K,Authorization:`Bearer ${K}`,"Content-Type":"application/json",Prefer:"return=representation",...(init.headers||{})}});if(!r.ok)throw new Error(await r.text());const t=await r.text();return t?JSON.parse(t):[]}
async function privacyKey(req:Request){const raw=[req.headers.get("cf-connecting-ip")||req.headers.get("x-forwarded-for")?.split(",")[0]||"unknown",req.headers.get("user-agent")||"unknown",SALT].join("|");const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(raw));return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function articleForSlug(value:string){const found=await rows(`resource_articles?select=id,slug,title,status&slug=eq.${encodeURIComponent(value)}&limit=1`);if(found[0])return found[0];const redirected=await rows(`resource_slug_redirects?select=article_id,resource_articles(id,slug,title,status)&old_slug=eq.${encodeURIComponent(value)}&limit=1`);return redirected[0]?.resource_articles||null}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{if(req.method==="GET"&&new URL(req.url).searchParams.get("command")==="sitemap"){const articles=await rows("resource_articles?select=slug,updated_at&status=eq.published&order=published_at.desc");const urls=articles.map((article:{slug:string,updated_at:string})=>`<url><loc>https://alignedprintscan.com/resources/${article.slug}/</loc><lastmod>${String(article.updated_at).slice(0,10)}</lastmod></url>`).join("");return new Response(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://alignedprintscan.com/resources/</loc></url>${urls}</urlset>`,{headers:{...cors,"content-type":"application/xml; charset=utf-8","cache-control":"public, max-age=900"}});}if(req.method!=="POST")return json({error:"Method not allowed."},405);const body=await req.json() as Record<string,unknown>,command=clean(body.command,40),key=await privacyKey(req);
 if(command==="list"){const data=await rows("resource_articles?select=id,title,slug,dek,is_featured,published_at,resource_categories(name,slug),resource_assets(public_url,alt_text)&status=eq.published&order=is_featured.desc,published_at.desc");return json({articles:data});}
 const article=await articleForSlug(slug(body.slug));if(!article||article.status!=="published")return json({error:"Published article not found."},404);
 if(command==="view"){await rows("resource_article_views?on_conflict=article_id,privacy_key,viewed_on",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates,return=minimal"},body:JSON.stringify({article_id:article.id,privacy_key:key})});return json({ok:true});}
 if(command==="helpfulness"){const recent=await rows(`resource_helpfulness?select=id&privacy_key=eq.${key}&submitted_at=gte.${encodeURIComponent(new Date(Date.now()-86400000).toISOString())}`);if(recent.length>=12)return json({error:"Feedback limit reached. Please try again tomorrow."},429);const helpful=body.helpful===true,reason=helpful?null:clean(body.reason,40),comment=helpful?null:clean(body.comment,1000);if(!helpful&&!['missing_detail','unclear','not_relevant','outdated','other'].includes(String(reason)))return json({error:"Choose a feedback reason."},400);await rows("resource_helpfulness?on_conflict=article_id,privacy_key",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({article_id:article.id,helpful,reason,comment,privacy_key:key,submitted_at:new Date().toISOString()})});return json({ok:true});}
 if(command==="feedback"){const name=clean(body.name,100),email=clean(body.email,254).toLowerCase(),message=clean(body.message,3000);if(name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||message.length<10)return json({error:"Enter a name, valid email, and a question of at least 10 characters."},400);const recent=await rows(`resource_feedback?select=id&privacy_key=eq.${key}&created_at=gte.${encodeURIComponent(new Date(Date.now()-3600000).toISOString())}`);if(recent.length>=3)return json({error:"Message limit reached. Please try again later."},429);const inserted=await rows("resource_feedback",{method:"POST",body:JSON.stringify({article_id:article.id,name,email,message,privacy_key:key})});await rows("admin_notifications",{method:"POST",body:JSON.stringify({event_type:"resource_feedback",severity:"action_required",title:"New Resource Center question",body:`A private question was submitted from ${article.title}.`,target_tab:"resources",target_url:`admin-dashboard.html#resources?feedback=${inserted[0]?.id||""}`,dedupe_key:`resource-feedback:${inserted[0]?.id}`})});return json({ok:true});}
 return json({error:"Unsupported command."},400);
}catch(error){console.error(error);return json({error:"The Resource Center service is temporarily unavailable."},500)}});
