import { renderFullTemplateEmail } from "../_shared/template-preview.mjs";

const U=Deno.env.get("SUPABASE_URL")||"",S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",RESEND=Deno.env.get("RESEND_API_KEY")||"",FROM=Deno.env.get("RESEND_FROM_EMAIL")||Deno.env.get("FROM_EMAIL")||"Aligned Print & Scan <hello@alignedprintscan.com>",SITE=(Deno.env.get("SITE_URL")||"https://alignedprintscan.com").replace(/\/$/,"");
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const generic="If an approved account is associated with this email, password reset instructions have been sent.";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const headers={apikey:S,Authorization:`Bearer ${S}`,"Content-Type":"application/json"};
async function rows(path:string,init:RequestInit={}){const r=await fetch(`${U}/rest/v1/${path}`,{...init,headers:{...headers,...(init.headers||{})}});const data=await r.json().catch(()=>[]);if(!r.ok)throw new Error(`database_${r.status}`);return data;}
async function sha(value:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,error:"Method not allowed."},405);let eventId="";try{
  const body=await req.json().catch(()=>({})),email=String(body.email||"").trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({ok:true,message:generic});
  const members=await rows(`organization_members?select=id,user_id,email,full_name,organization_id,organizations!inner(organization_name,status)&email=eq.${encodeURIComponent(email)}&status=eq.active&limit=1`),member=members[0];if(!member?.user_id||member.organizations?.status!=="active")return json({ok:true,message:generic});
  const bucket=Math.floor(Date.now()/600000),fingerprint=await sha(`${email}:${bucket}`),existing=await rows(`business_password_recovery_events?select=id,delivery_state&request_fingerprint=eq.${fingerprint}&limit=1`);if(existing.length)return json({ok:true,message:generic});
  const event=(await rows("business_password_recovery_events?select=id",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({organization_id:member.organization_id,organization_member_id:member.id,recipient_email:email,request_fingerprint:fingerprint,delivery_state:"processing"})}))[0];eventId=event.id;
  const linkResponse=await fetch(`${U}/auth/v1/admin/generate_link`,{method:"POST",headers,body:JSON.stringify({type:"recovery",email,redirect_to:`${SITE}/business-reset-password.html`})}),linkData=await linkResponse.json().catch(()=>({}));if(!linkResponse.ok||!linkData?.action_link)throw new Error("recovery_link_failed");
  const templates=await rows("message_templates?select=*&template_key=eq.business_password_reset&active=eq.true&limit=1"),template=templates[0];if(!template)throw new Error("recovery_template_missing");const rendered=renderFullTemplateEmail({template,context:{siteUrl:SITE,actionUrl:linkData.action_link,resetUrl:linkData.action_link,customer:{display_name:member.full_name},serviceName:"Business Portal",reference:"",requestedDate:"",requestedTime:""}});
  if(!RESEND)throw new Error("email_provider_unavailable");const sent=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${RESEND}`,"Content-Type":"application/json"},body:JSON.stringify({from:FROM,to:[email],subject:rendered.subject,html:rendered.html,text:template.text_template})}),sentData=await sent.json().catch(()=>({}));if(!sent.ok)throw new Error("email_delivery_failed");
  await rows(`business_password_recovery_events?id=eq.${event.id}`,{method:"PATCH",body:JSON.stringify({delivery_state:"sent",provider_id:String(sentData.id||"").slice(0,300)||null,delivered_at:new Date().toISOString()})});
  await rows("organization_activity",{method:"POST",body:JSON.stringify({organization_id:member.organization_id,event_type:"business_password_reset_email_sent",title:"Business Password Reset Email Sent",detail:"Password reset instructions were sent to an authorized Business Portal user.",actor_type:"system",metadata:{organization_member_id:member.id,recipient_email:email,recovery_event_id:event.id}})});
  await rows("admin_notifications",{method:"POST",body:JSON.stringify({event_type:"business_password_reset_email_sent",severity:"info",title:"Business Password Reset Email Sent",body:`Password reset instructions were sent to an authorized Business Portal user for ${String(member.organizations.organization_name||"a Business Account").slice(0,180)}.`,target_tab:"customer",dedupe_key:`business-password-reset:${event.id}`})});
  return json({ok:true,message:generic});
}catch(error){const failure=error instanceof Error&&/^(recovery_link_failed|recovery_template_missing|email_provider_unavailable|email_delivery_failed)$/.test(error.message)?error.message:"internal_failure";if(eventId)await rows(`business_password_recovery_events?id=eq.${eventId}`,{method:"PATCH",body:JSON.stringify({delivery_state:"failed",failure_code:failure})}).catch(()=>null);console.error("Business password recovery failed",failure);return json({ok:true,message:generic});}});
