/** Secure additional customer document upload after email verification. */
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const U=Deno.env.get("SUPABASE_URL")||"";const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";const MAX=10*1024*1024;
function json(b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...corsHeaders,"Content-Type":"application/json"}})}
async function db(path:string,init:RequestInit={}){return fetch(`${U}/rest/v1/${path}`,{...init,headers:{apikey:K,Authorization:`Bearer ${K}`,"Content-Type":"application/json",Prefer:"return=representation",...(init.headers||{})}})}
async function rows(r:Response){if(!r.ok)throw new Error(await r.text());return r.json()}
function safeName(n:string){return n.replace(/[^a-z0-9._-]+/gi,"-").replace(/^-+|-+$/g,"").slice(0,120)||"document"}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});try{const b=await req.json();const id=String(b.request_id||"");const email=String(b.email||"").trim().toLowerCase();const files=Array.isArray(b.files)?b.files:[];if(!id||!email||!files.length)throw new Error("Request, email, and at least one file are required.");
const rr=await rows(await db(`service_requests?select=id,customers(email)&id=eq.${id}&limit=1`));const r=rr?.[0];const c=Array.isArray(r?.customers)?r.customers[0]:r?.customers;if(String(c?.email||"").toLowerCase()!==email)return json({ok:false,error:"The email address does not match this request."},403);
const created=[];for(const f of files){const name=safeName(String(f.name||"document"));const mime=String(f.type||"application/octet-stream");const raw=Uint8Array.from(atob(String(f.base64||"")),x=>x.charCodeAt(0));if(!raw.length||raw.length>MAX)throw new Error(`${name} is empty or larger than 10 MB.`);const path=`${id}/additional/${crypto.randomUUID()}-${name}`;const up=await fetch(`${U}/storage/v1/object/service-request-files/${path}`,{method:"POST",headers:{apikey:K,Authorization:`Bearer ${K}`,"Content-Type":mime,"x-upsert":"false"},body:raw});if(!up.ok)throw new Error(await up.text());const rec=await rows(await db("request_files",{method:"POST",body:JSON.stringify({service_request_id:id,file_name:name,file_path:path,file_type:mime,file_size:raw.length,uploaded_by:"customer",document_category:String(b.category||"additional"),is_active:true})}));created.push(rec?.[0]);}
await db("request_timeline_events",{method:"POST",body:JSON.stringify({service_request_id:id,event_type:"documents_uploaded",title:"Additional documents uploaded",detail:`Customer uploaded ${created.length} additional document(s).`,actor_type:"customer",metadata:{file_count:created.length}})});return json({ok:true,files:created});}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},400)}})
